### ISSUE TITLE
Support other database 

### ISSUE THREAD

**Issue by gguan** [protegeproject/webprotege#103]
Hi,

We want to set up our own protege web server but we have license issue with MongoDB that we are not allowed to install MongoDB in the company server.

It would be good if the database interface is more abstract and user can possibly develop plugins to replace MongoDB storage.

Thanks,

Guan

**Comment by matthewhorridge** [comment]
Sorry, we don't have the resources to do this.  Closing the issue for now.  This may be revisited in the future.
