### ISSUE TITLE
Download ontology from ontology list does not work

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#104]
Clicking on the Download icon in the ontology list on the WebProtege tab produces an invalid zip file.

The generated URL (that does not work):
http://webprotege.stanford.edu/download?ontology=987d9f04-f085-4534-be1f-8619aa5f0c4d&revision=9223372036854775807&format=owl

Downloading from the Revisions portlet works fine. Generated URL:
http://webprotege.stanford.edu/download?ontology=987d9f04-f085-4534-be1f-8619aa5f0c4d&revision=113&format=owl

The URL without the revision argument set, also works:
http://webprotege.stanford.edu/download?ontology=987d9f04-f085-4534-be1f-8619aa5f0c4d&format=owl

**Comment by matthewhorridge** [comment]
The mechanism has changed a lot since 2015.  We've not had complaints about download URLs recently.  Closing this issue as stale.
