### ISSUE TITLE
Support mongodb authentication

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#113]
This is a request from the Protege mailing list on 3/18/2014 (see at the end).

Currently WebProtege uses the default user with no authentication when connecting to mongodb. The request is to support authentication (connect to mongo db with a specific user/pass).

Easy mongodb auth overview here:
http://learnmongo.com/posts/quick-tip-mongodb-users/

mongodb authentication:
http://docs.mongodb.org/manual/core/access-control/

Request:
"I'm trying to run the current version of Webprotege from my Openshift (a
Public PaaS cloud based solution). It runs fine with the old version of
Webprotege.  However, I'm having difficulty with new version, particularly
with mongodb.

Openshift automatically installs the mongodb cartridge for me on the
application, but there is a username and password associated with mongodb.
Is there anyway of declaring these variables in the webprotege.properties
file?  Because when I tried running it with just changing the mongodb.host
to my mongodb's host, it does not work. I get the usual "WebProtege could
not connect to mongodb. Please check that the mongod daemon is either
running on the default host (localhost) and default port (27017), or that
the mongod daemon is running on a custom host and port and that you have
specified the custom host and port in the protege.properties with the
parameters mongodb.host and mongodb.port" error."

**Comment by nandana** [comment]
I ran into the same issue when setting up the Web Protege. Does Web Protege support mongodb authentication now?

**Comment by nandana** [comment]
@matthewhorridge if this is not supported, can you please point me to where the DB connection is made so that I can patch it myself as this has become a blocker for us. Thanks a lot!

**Comment by dabougie** [comment]
Has there been any progress on this, or are there any concrete plans to address this in a future release?

**Comment by matthewhorridge** [comment]
Will make this a priority and try to push a fix for this by tomorrow.

**Comment by matthewhorridge** [comment]
Heads up...

Pre-release here https://github.com/protegeproject/webprotege/releases/tag/v4.0.0-beta-2

The relevant properties to add to ```webprotege.properties``` are:

```properties
mongodb.auth.username=<username>
mongodb.auth.password=<password>
mongodb.auth.source=<name of database containing authentication information>
```
