### ISSUE TITLE
Direct link does not work

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#144]
Direct link to an entity in a given ontology that one can get for example from the context menu on the class tree, is not working properly.
For example, user reported that the link:
http://webprotege.stanford.edu/?ontology=bf6f65d5-fcaf-494a-b472-fe881a358107&tab=IndividualsTab&id=http%3A%2F%2Fwebprotege.stanford.edu%2FR76LnJgya0KwEWDgLoHdEJN
is not bringing one to the "Magnetic Storage" entity, where it suppose to.

**Comment by matthewhorridge** [comment]
Overhauled and fixed in 3.0.0.
