### ISSUE TITLE
Feature Request - message other users from discussion threads

### ISSUE THREAD

**Issue by dosumis** [protegeproject/webprotege#150]
On Google Docs or GitHub, I can message another user by mentioning them in the text of a comment/ticket (e.g @matthewhorridge ).  It is difficult to engage other editors in discussion on threads without either this function or the ability to link to comment threads (which presumably is needed if a generated mail is to link back to the relevant discussion).

**Comment by matthewhorridge** [comment]
Implemented in 3.0.0
