### ISSUE TITLE
The grid widget does not honor the ont_type

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#153]
This bug report refers to the grid widget (http://protegewiki.stanford.edu/wiki/PropertyFormPortlet#Using_grids_.28tables.29):

(1): when creating a new individual from the grid widget, this individual should be typed to the class set in the configuration property "ont_type"

(2): when adding an existing value, the popup panel should offer by default the individuals of "ont_type" (the panel has a checkbox to show all individuals)

**Comment by matthewhorridge** [comment]
Stale.  Forms are being completely reimplemented.
