### ISSUE TITLE
Disjoint classes axioms cannot be edited

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#16]
There is no functionality for editing disjoint classes axioms.  We need to consider nary disjoint classes axioms.

**Comment by NataliaDiaz** [comment]
How can this be activated/shown in webprotege?

**Comment by matthewhorridge** [comment]
Add the "OWL Entity Description Editor" view by clicking on a tab menu and choosing it in the popup window.  Once you press "OK" you'll get a cursor and some highlighting showing you how you can placed the view in the interface.  Place it where you like.

<img width="480" alt="wp1" src="https://user-images.githubusercontent.com/488607/45696042-8a13de80-bb17-11e8-9a97-1882382f7006.png">


You can add disjoints by using the DisjoingWith: keyword followed by a list of classes that should be disjoint e.g.

<img width="592" alt="wp2" src="https://user-images.githubusercontent.com/488607/45696163-d3642e00-bb17-11e8-8fb8-7d4a3c6ee4b8.png">
