### ISSUE TITLE
Classes sometimes loose their display label

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#182]
Very hard to reproduce, it seems to be happening right after class creation, and a "can't find path to root" exception is thrown on the server. Instead the IRI is shown.

This issue may be related to #162 (might be the same bug).

http://webprotege.stanford.edu/#Edit:projectId=381a123f-ba2a-42be-bff8-5fbca866898d

![screenshot - 09242014 - 04 16 42 pm](https://cloud.githubusercontent.com/assets/2709502/4397344/2d58bfa4-4441-11e4-89c8-d56447aaaf8e.png)

**Comment by matthewhorridge** [comment]
The creation mechanism has changed a lot over the last year or two.  Marking this as stale.
