### ISSUE TITLE
Drag and Drop is not available in the property hierarchy

### ISSUE THREAD

**Issue by HarlanH** [protegeproject/webprotege#22]
Hi. I mistakenly created a Property in the wrong place in the property hierarchy. It doesn't seem like the UI lets me move that property to the right place. It does look like I can move Classes elsewhere in that hierarchy, so I was a bit surprised to see this. As it is, I think the only thing I can do is to delete the property and recreate it in the right place. Would love to see drag-and-drop functionality work here.

**Comment by matthewhorridge** [comment]
Implemented in WebProtege 3.0.0
