### ISSUE TITLE
Upgrade GWT

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#224]
From the mailing list:

I noticed the other day that the GWT Developer Plugin is now deprecated by Google, due to the deprecation of the NPAPI (see wording at https://chrome.google.com/webstore/detail/gwt-developer-plugin/jpjpnpmbddbjkfaccnmhnkdgjideieim and http://www.chromium.org/developers/npapi-deprecation). 

The WebProtégé Maven POM in GitHub uses GWT 2.5.1, which as far as I understand, requires/makes use of the now deprecated GWT Developer Plugin. Getting WebProtégé development working at the moment therefore requires the use of older versions of Firefox in which the plugin can still be loaded.

Has anyone had success running WebProtégé with newer versions of GWT (2.6.1 or 2.7)? Or is there some other workaround available that would let me use a more recent browser with GWT 2.5.1?

**Comment by matthewhorridge** [comment]
Just an update on this.  I have it compiling with 2.7.0 (in a local branch).  Everything seems o.k.  I'll push an update soon.

**Comment by matthewhorridge** [comment]
... another thing.  The maven plugin supports superdevmode (I think).

**Comment by matthewhorridge** [comment]
Done.
