### ISSUE TITLE
Class hierarchy does not always refresh when deleting classes

### ISSUE THREAD

**Issue by HarlanH** [protegeproject/webprotege#23]
It seems that if I delete a class by pressing the delete button, there are some UI issues. The node doesn't automatically disappear. If I press the refresh button (in the UI, not the browser), in at least some cases, ALL classes disappear from the UI, which is rather scary. Pressing refresh again seems to bring them back as expected.

**Comment by matthewhorridge** [comment]
Reimplemented all hierarchies in WebProtege 3.  This is much more robust now.
