### ISSUE TITLE
Sharing using an email address is not working

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#232]
Sharing an ontology using an email address is not preserved. Steps to reproduce:
- Open the Share dialog for some ontology,
- Write an email address in the text area
- Select any permission (e.g., can read, write, etc.), and click on the Add button.
- The new permission is shown correctly in the dialog.
- Close the Share dialog by pression OK
- Reopen the Share dialog -> the email permission is gone

Workaround:
Sharing using an account works fine. Ask the person you want to share with to create a user account on WebProtege, and then share with that user account.

**Comment by matthewhorridge** [comment]
Stale issue.  Share using accounts.
