### ISSUE TITLE
The MetaProject API is slow

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#239]
With the large number of projects that we have in WebProtege now, checking to see if a user can list them takes a long time (8 seconds on my laptop).  Some profiling revealed that getting the groups for a user is particularly slow - the call to wrap Protege instance takes 50% of the time.

Some of the code in WebProtege could be optimised, but we should also consider other solutions (e.g. some kind of MongoDB based solution).

**Comment by artamoeini** [comment]
Hi Matt

we have problem slow webprotage after working  hours ..
your application have problem in loading subclass . i think you must show just special instance client request tahat . not load all child of parent . for example for a ontology university project . we use webprotage and now we have 40.000 subclass on a class ( or subject) . we need  tree schema and we can't make a different class and declare subclass on there ( it's not on our case ) ... google working on a project name is fast tree .. it's declare a instance of tree seem area and just load a special area client loaded this . (fast tree gwt)
and you must know it's problem can stop web server . i test webprotage with another web server . jetty . weblogic and jboss . ( tomcat must config and has problem if head is full and web server stop)

please say to me if you have a way for problem memory load in webprotage

I'm Linux administatror not programmer and you can see my resume at it.toolbox/ mohammad.moeini  

i think i can test your project and have a probelm in high-load .now we have at this plan

**Comment by matthewhorridge** [comment]
The meta project has bitten the dust in 3.0.0.  Stale issue.
