### ISSUE TITLE
Drag-n-drop in classes tree does not behave as expected

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#241]
From the mailing list (03/05/2015):
1.  The user interface appears to offer the user a choice of either 
   (1) moving a class in the hierarchy to a new parent class, or 
   (2) inserting a class into a list between two of its intended siblings, without making it a child of the class above it. But this turns out to be a false choice.

This distinction is clearly shown to the user. In the first case, when the class name is dragged on top of another class name, a popup appears before the user releases the mouse button to drop the class onto its new parent class. This popup gives you a hint that this is the action you are performing. Here I am attempting to move the class “Antipsychotics” to a new parent of “Antidepressants":

![image001](https://cloud.githubusercontent.com/assets/2709502/6516445/d14efacc-c346-11e4-8530-0362e76f9d47.jpg)

Then I get a popup dialog asking me to confirm: “Are you sure you want to move Antipsychotics from parent Drug to parent Antidepressants?” I click OK, and the class moves.

So far, so good, right? Now let’s look at the second way of dragging and dropping classes in the hierarchy. Let’s say for some reason I want to move Aspirin from being a child of its current parent, Antiplatelet Medicines, to being a child of its current grandparent, Drugs. But instead of dragging it directly on top of the class name Drugs, I want to drag it to its rightful place in the alphabetical class list of Drugs, in between ARBs and Atomoxetine. WebProtege appears to let me do that:

![image002](https://cloud.githubusercontent.com/assets/2709502/6516452/e237366a-c346-11e4-8a90-6b0349e054bd.png)

 See how that line appears between ARBs and Atomoxetine? And how that little icon shows up to tell me that I’m inserting a class between two other classes in a list? (Contrast that with the (+) icon in the last screenshot.) But as soon as I release the mouse button to drop Aspirin into its new location, there’s an indication that something isn’t right:

![image003](https://cloud.githubusercontent.com/assets/2709502/6516458/eb885c9e-c346-11e4-88a3-25c353e7eb85.jpg)

Sure enough: I haven’t inserted Aspirin into the Drugs list at all. Instead, I’ve added it as a child of the class just above the place I intended to drop it: ARBs. The behavior is just the same as if I’d dropped it on top of the class ARBs – despite the fact that the class hierarchy now shows Aspirin as a sibling of ARBs! The clue that the term has landed in the wrong place (besides the notification dialog) is that a + has appeared next to ARBs, which previously had no children. When we look at the class description, we can confirm that it has indeed been added as a subclass of ARBs.
1.  Now let’s say I try to correct this mistake by moving Aspirin back to its old location. I will find that although Antiplatelet Medicines has been added to the SubClassOf list, ARBs is still there! Surely that’s not desirable behavior either.

**Comment by matthewhorridge** [comment]
Stale issue.  Closing this because it no longer applies because we no longer use this tree.
