### ISSUE TITLE
Can't set user specific ranges in the New Entity settings (Auto-generated OBO style ID)

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#254]
The table for setting the user specific ranges is not displayed properly in the New Entity Settings.

![screenshot - 04012015 - 04 12 53 pm](https://cloud.githubusercontent.com/assets/2709502/6954752/31cd856e-d88a-11e4-9126-5f62929894ac.png)

**Comment by bobular** [comment]
I see this too.

I would like to be able to set a starting index number manually because the automatically generated one is clashing with an existing "alt_id" in the source OBO file.

VBcv ontology, project ID:
5e2b0b97-40d9-4520-8c75-5007b62619a2

thanks
Bob

**Comment by bobular** [comment]
Hello, is there any news on this issue?

**Comment by matthewhorridge** [comment]
This will be available in WebProtege 3.0.0 (it's fixed).  We don't have a date for the release of this yet though.
