### ISSUE TITLE
WebProtege loses the session after a refresh

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#256]
Reported from the short course:

Every time you press the Refresh on your Browser , it loses the Session , and you have to re-login. Someone can easily not notice it and experience issues. If it is obligatory to lose the Session for some reason upon refresh , it would be better to sent the user in the Home Page and not directly back to the ontology he was working to.

**Comment by ariutta** [comment]
+1

**Comment by matthewhorridge** [comment]
This is something to do with out setup with apache on webprotege.stanford.edu.  Running locally, I don't have this problem.

**Comment by matthewhorridge** [comment]
We might need to tinker with ProxyPassReverseCookieDomain

**Comment by matthewhorridge** [comment]
This is a local config issue.  The correct apache settings need to be present and the tomcat root path needs setting correctly.
