### ISSUE TITLE
Enhancements to the notes portlet

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#257]
From the short course:

1) Comments should be hyper-linked to where they were made , so that if you click on them it will transfer you to the specific class , individual , etc. OR it could popup a panel with the discussion around that comment and some additional info on the header regarding 
the location of the Comment , date it was created etc.

2) A simple onMouseOver Tooltip on the username that will display some info regarding the user making that specific comment.

3) Some additional info on the Comments Display. Like Always include the Class , Individual , etc that this comments reefers to. Now it seems to have the Class , Individual , only on the first created comment. All the rest (Follow Ups) lack this info.

**Comment by matthewhorridge** [comment]
Hyperlinking is now supported in comments.  Not implementing the user mouse over for now.  Please open a separate issue if this is really important.
