### ISSUE TITLE
A fresh meta-project should be created if none exists

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#259]
This currently isn't working in the code contained in master.  It works in the current release.

**Comment by hammar** [comment]
Posting workaround here as well in case it is not immediately obvious from the issue description:

1) check out tag 2.5.0 and start it with an empty data directory and clean mongodb install
2) create a project in v2.5.0 (requires using an old Firefox that works with the now deprecated GWT browser plugin to access it)
3) shut down v2.5.0
4) check out latest commit from master branch
5) start that version against the same data directory and mongodb
