### ISSUE TITLE
The simple UI should show the corresponding entity for the annotation values that are IRIs

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#262]
Derived from the mailing list:

If an annotation property has as value an IRI (that corresponds to an entity in the ontology), the simple UI should show the corresponding entity, like in Protege desktop. Currently, it is showing the IRI and the user cannot navigate to the corresponding entity in WP.

![screenshot - 04212015 - 10 14 37 am](https://cloud.githubusercontent.com/assets/2709502/7258227/ed07212a-e80f-11e4-9ce3-20dd36a03be4.png)

**Comment by matthewhorridge** [comment]
Works - apart from the fact that an odd warning message is displayed....

<img width="482" alt="entitylinking" src="https://user-images.githubusercontent.com/488607/32866710-ebab9f70-ca1d-11e7-84bc-e69af0339662.png">
