### ISSUE TITLE
Individuals list does not follow class selection after being clicked

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#272]
To reproduce.  Assume there are classes A and B and that A has an instance i.  Select A.  i is displayed in the individuals list.  Click on i.  Select B in the class tree.  The individuals list does not get updated.

**Comment by hammar** [comment]
This also has the side-effect that new individuals sometimes are not assigned to the intended/selected class.

**Comment by anton-z-s** [comment]
Is there no way to have CLASS_SELECTION_FIELD working? It seems important feature.
Are you planning to continue developing this awesome project?
