### ISSUE TITLE
Entity Description Editor generates error 500 on any text entry

### ISSUE THREAD

**Issue by hammar** [protegeproject/webprotege#274]
Steps to reproduce:
1) Open an existing project
2) Open the OWL Entity Description Editor and place in main column.
3) Select a class.
4) Type something in the OWL Entity Description Editor

Result: WebProtégé shows a Internal Server Error dialog box, referring to an error 500 on the server. The server throws an uncaught exception.
Expected result: User should be able to enter Manchester OWL axioms and once done, persist those to the ontology.

**Comment by matthewhorridge** [comment]
Easily reproduced.  Thanks for the bug report.

**Comment by hammar** [comment]
Thanks - as always, awesome work! I'm starting to feel I should be paying you guys something for providing such excellent support to the community :)
