### ISSUE TITLE
Restarting Tomcat causes metaproject data loss

### ISSUE THREAD

**Issue by hammar** [protegeproject/webprotege#279]
When restarting Tomcat on two different machines running latest WebProtégé build (one on Tomcat 6 and the other on Tomcat 7), data is lost from the metaproject, causing users to no longer see their projects, or the projects they have been invited to collaborate on. The projects still exist on disk, but user group membership is actually removed from the metaproject.pins file. I've on one occasion also seen a user account be removed from the metaproject.

There are a bunch of SEVERE errors in the Tomcat log that may be related: https://gist.github.com/hammar/65dc0d4ef4a9f90884ca

**Comment by matthewhorridge** [comment]
Hi Karl,

Do you have exact steps to reproduce this problem?  I've just tried it but could reproduce the failed save.  I started a local version of webprotege using Tomcat 8.  Added a user as a viewer to an existing project and then shut down Tomcat.  The meta project was saved as expected and the sharing settings persisted.

I get the warnings, but this is related to something else (to do with Guice and Guava).

We really need to replace the meta project.... it's on our todo list.

**Comment by hammar** [comment]
Hi,

Steps to reproduce, works every time for me:

1. Compile WebProtégé

    mvn -Pdeployment -Dapplication.host=wp.xd-protege.com -Ddata.directory=/var/tomcat/webprotege package

2. Deploy WP to Tomcat 6

    mv target/webprotege-2.6.0-SNAPSHOT ~/wp.xd-protege.com/ROOT

3. Log in to WebProtégé (had an account since previous version, so no need to create new)

4. Create a project titled "Metaproject test 1" (or 2, 3, etc..)

5. Check that project is in metaproject.pins and access rights are granted

6. On server, restart Tomcat:

    sudo /etc/init.d/tomcat6 restart

7. Refresh WebProtégé

8. Be confused about where the project went..?

9. Note that project ID is not listed in metaproject.pins any longer

9. Be further confused

The server in question is running Ubuntu 14.04 LTS. Tomcat 6 is installed via apt/dpkg. As I mentioned, the same thing happens on another server running Tomcat 7 (apart from that and some data paths, the two machines are identical). If you would like access to the machine to see the logs or other specifics in action I can fix that - in that case, send me a S/MIME signed email to karl.hammar@icloud.com and I'll reply with S/MIME encrypted credentials. Or if you prefer a text message, let me know the number I should send to.

**Comment by hammar** [comment]
Note: I cannot replicate when running from Eclipse using devmode

**Comment by matthewhorridge** [comment]
Do you get these lines printed to the terminal?

```
[WebProtege] Saving meta-project now.                                                                                                                                                [Fri Jun 26 10:56:26 PDT 2015]
[WebProtege] Saved meta-project in 39 ms                                                                                                                                             [Fri Jun 26 10:56:26 PDT 2015]
[WebProtege] Saving meta-project now.                                                                                                                                                [Fri Jun 26 10:56:26 PDT 2015]
[WebProtege] Saved meta-project in 19 ms  
```

I've just noticed that the meta project is being saved twice when the application is shutdown, but this should cause any loss.

**Comment by hammar** [comment]
Yup:

[WebProtege] Saving meta-project now.                                                                                                                                                [Fri Jun 26 19:47:42 CEST 2015]
[WebProtege] Saved meta-project in 117 ms                                                                                                                                            [Fri Jun 26 19:47:42 CEST 2015]
[WebProtege] Saving meta-project now.                                                                                                                                                [Fri Jun 26 19:47:42 CEST 2015]
[WebProtege] Saved meta-project in 75 ms                                                                                                                                             [Fri Jun 26 19:47:42 CEST 2015]

**Comment by matthewhorridge** [comment]
o.k. thanks.  We're looking into it.  While I cannot seem to reproduce it using my setup, there have been substantial changes under the hood and it's possible that these have caused some upset.

**Comment by hammar** [comment]
I've now tried a variety of commits, back to Feb 26, and this occurs every time. So I'm starting to think perhaps this is a configuration issue with Tomcat and/or Ubuntu, rather than a WP issue per se. But it's odd that I' seeing it on two machines..

**Comment by matthewhorridge** [comment]
We are going to try and replicate your tomcat and linux setup here as see if we can spot anything.

**Comment by matthewhorridge** [comment]
We just performed a test using Ubuntu 14.04, Java 8 and Tomcat 7 and we couldn't reproduce the failure to save the meta project.

What we did notice is that, after a restart and then a browser refresh, when using FireFox (but not Chrome or Safari), the UI was still showing the user as logged in (when in fact the user wasn't logged in), but the project was not displayed in the list.  When logging out and logging in the user was properly logged in and the project was displayed in the list.  However, the meta project was still saved and the pins file was written out correctly.

If you want to email us your logs (catalina.out) privately we will scour those for information.

**Comment by hammar** [comment]
Some more debug info. Logs are at https://gist.github.com/hammar/a932cd1787c9569f4160 (unfortunately this machine for some reason has a Swedish locale set, so some timestamps might not make a lot of sense to you: but "ALLVARLIG" means "SEVERE" and "EM" means "PM": 

I'm going to try and set up VMWare image and see if I can replicate on a third machine. But will do that next week, time here is now past 10 PM.

First I check that the metaproject.pins contains the project (114ed... is the ID of the test project in question):

`karl@xd-protege:/var/tomcat/webprotege/metaproject$ cat ~/metaproject.pins | grep 144ed620-380a-485c-8c83-1cd1134b4e48
([144ed620-380a-485c-8c83-1cd1134b4e48] of  Project
	(name "144ed620-380a-485c-8c83-1cd1134b4e48")
([144ed620-380a-485c-8c83-1cd1134b4e48_Commenters] of  Group
	(name "144ed620-380a-485c-8c83-1cd1134b4e48_Commenters"))
([144ed620-380a-485c-8c83-1cd1134b4e48_None] of  Group
	(name "144ed620-380a-485c-8c83-1cd1134b4e48_None"))
([144ed620-380a-485c-8c83-1cd1134b4e48_Readers] of  Group
	(name "144ed620-380a-485c-8c83-1cd1134b4e48_Readers"))
([144ed620-380a-485c-8c83-1cd1134b4e48_Writers] of  Group
	(name "144ed620-380a-485c-8c83-1cd1134b4e48_Writers"))
		[144ed620-380a-485c-8c83-1cd1134b4e48_Writers])
	(allowedGroup [144ed620-380a-485c-8c83-1cd1134b4e48_Readers])
	(allowedGroup [144ed620-380a-485c-8c83-1cd1134b4e48_Commenters])
	(allowedGroup [144ed620-380a-485c-8c83-1cd1134b4e48_Writers])
	(allowedGroup [144ed620-380a-485c-8c83-1cd1134b4e48_None]))`

Modification date when project was created and metaproject file written (21:47):

`drwxr-xr-x 2 tomcat6 tomcat6    4,0K jun 26 21:47 .
drwxr-xr-x 6 tomcat6 webprotege 4,0K jun 26 20:44 ..
-rw-r--r-- 1 tomcat6 tomcat6     29K jun 26 21:47 metaproject.pins
-rw-r--r-- 1 tomcat6 tomcat6    6,8K jun 26 21:47 metaproject.pont
-rw-r--r-- 1 tomcat6 tomcat6    119K jun 26 21:47 metaproject.pprj`

Shutting down Tomcat:

`karl@xd-protege:/var/tomcat/webprotege/metaproject$ sudo /etc/init.d/tomcat6 stop
[sudo] password for karl: 
 * Stopping Tomcat servlet engine tomcat6                                                                                                                                       [ OK ]`

After stopping Tomcat the metaproject modification date is updated (21:48) even though no changes have been performed in the WP UI at that timestamp:

`karl@xd-protege:/var/tomcat/webprotege/metaproject$ ls -lah
totalt 164K
drwxr-xr-x 2 tomcat6 tomcat6    4,0K jun 26 21:48 .
drwxr-xr-x 6 tomcat6 webprotege 4,0K jun 26 20:44 ..
-rw-r--r-- 1 tomcat6 tomcat6     27K jun 26 21:48 metaproject.pins
-rw-r--r-- 1 tomcat6 tomcat6    6,8K jun 26 21:48 metaproject.pont
-rw-r--r-- 1 tomcat6 tomcat6    119K jun 26 21:48 metaproject.pprj`

At this point the metaproject file no longer contains the project:

`karl@xd-protege:/var/tomcat/webprotege/metaproject$ cat metaproject.pins | grep 144ed620-380a-485c-8c83-1cd1134b4e48
karl@xd-protege:/var/tomcat/webprotege/metaproject$`

**Comment by hammar** [comment]
There appears to be a problem with mongodb. Don't know if that is related? The client seems to work well from the command line though, and apart from this issue, WebProtégé works as expected..

**Comment by hammar** [comment]
Oh, and also: as a result of my playing around with different versions of WP this log in question is for an older commit (9e29836e14364f4840fc284faf43997791237d19), not the most recent. I can revert to the most recent if such a log would be more useful. But first I'll try to replicate in my VM as mentioned above.

**Comment by matthewhorridge** [comment]
Hi Karl,

Thank a lot for the logs.  

There's something curious about the logs in that webprotege seems to be saving the metaproject multiple times and being disposed multiple times.  

The only way we could reproduce this here, and also reproduce the symptoms of disappearing projects etc. that you describe above, is if we have multiple webprotege webapps in the same servlet container e.g. webprotege1 and webprotege2 (otherwise exactly the same jar).  

Is it possible that this duplication applies in your case?  We're just wondering if you have copied in the snapshot under two different names by accident.  As I say, we want to double check this because this is the only way we can reproduce everything that you've described above.

Thanks,

Matthew

**Comment by hammar** [comment]
Hi,

I think you have found the issue. In order to be able to rapidly revert to a known working version when upgrading, I've made it habit to rename the old instance directory and keep it around, rather than overwrite it. I would have thought that since no changes are being performed in the inactive older version, it would not write anything to the metaproject, but it seems this is a faulty assumption. After removing all older versions from the servlet container, I can no longer replicate the issue. Perhaps a write lock feature on the relevant data files/directories could be useful to consider for future versions?  Many thanks for helping resolve this, and I hope it didn't take too much of your time.

/Karl

**Comment by matthewhorridge** [comment]
Glad that it's been resolved.

> Perhaps a write lock feature on the relevant data files/directories could be useful to consider for future versions? 

Yes, I was also thinking about this yesterday.  I'll file an issue for it.
