### ISSUE TITLE
Allow display language tag to be specified

### ISSUE THREAD

**Issue by krisklykens** [protegeproject/webprotege#28]
(Was: Allow 'Display name' contents to display non-english terms)

Value from rdfs:label is used for display name. This is automatically the attribute with 'en' language attribute.
It would be an improvement if can choose a different language for defaulting the display name to. In our case this could easily be a server configuration setting (rather than a project configuration setting).

**Comment by muichkine** [comment]
+1

**Comment by matthewhorridge** [comment]
Hope this was worth waiting for.  You can now set the display property and language at the project level (see project settings) and these can be overridden at a local (browser) level.
