### ISSUE TITLE
Built in tabs are blank

### ISSUE THREAD

**Issue by Fersox** [protegeproject/webprotege#286]
for example:

1  Close the "Individuals tab" by the tools "  add tab ".
2  Add " Individuals tab " by the tools " add tab ".
3.the "Indididuals tab" content is blank.
![image](https://cloud.githubusercontent.com/assets/7875693/9347474/8578ef2e-465c-11e5-8b3a-cf03e927410a.png)

**Comment by matthewhorridge** [comment]
No longer applicable to WebProtege 3.0.0.
