### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by ariutta** [protegeproject/webprotege#289]
Hello,

I'm running into a bug with the upload functionality. I created an ontology named "gpml" at the webprotege instance hosted at http://webprotege.stanford.edu/, opened the ontology, clicked "Project" -> "Upload and merge" and then selected an RDF file that exists locally my computer. The RDF file is the same as [this one](https://github.com/wikipathways/WpVocabularies/blob/master/OWL/GPML.rdf). The loading indicator pops up and then goes away, but the "Upload ontologies" modal remains open while my browser sends POST requests to 
http://webprotege.stanford.edu/webprotege/dispatchservice

The status of the requests is 200 and the size is 381 B. So far, it's sent over 100 of these requests from a single upload attempt.

I'm not sure whether this is a general webprotege bug or just a bug with the instance hosted at http://webprotege.stanford.edu/.

I'm using Chrome Version 45.0.2454.85 (64-bit) on OSX 10.8.5.

**Comment by matthewhorridge** [comment]
This functionality needs some documentation, but there is a requirement that any uploaded ontology must have the same ontology id (IRI and version IRI) as some ontology in the project.  I'm guessing that this isn't the case here.  I'll file an issue to produce a warning if there are no matches.

As for the requests, I suspect these are just the normal requests for retrieving events from the server and most of them have nothing to do with the upload (there is one every 10 seconds if I recall correctly).
