### ISSUE TITLE
Add "Forgot username" option

### ISSUE THREAD

**Issue by yayamamo** [protegeproject/webprotege#292]
When trying to sign in, I forgot my user name, and I cannot find a way to remind me.
I know my email address, so it would be nicer if webprotege provides this option.

**Comment by matthewhorridge** [comment]
I think that the user name should be sent in the email with the fresh password.

**Comment by matthewhorridge** [comment]
I've opened a fresh issue for this https://github.com/protegeproject/webprotege/issues/293
