### ISSUE TITLE
Send username in the reset password email 

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#293]
A user password can be reset by the user supplying their email address.  This causes an email with a fresh password to be sent to the user.  This email should also contain the username, because users occasionally forget this and there is no way to retrieve it at the moment.

**Comment by csnyulas** [comment]
It is not clear from the user interface that people can retrieve their user name in this way. If we want to keep the current implementation, then we should rename the link to something more suggestive, like "Forgot user name or password", and mention in the pup-up dialog that they will get their user name sent to them through the reset password procedure.
It may be cleaner if these two functionalities would not be tied together.

**Comment by tudorache** [comment]
The wrong user name is sent in the reminder email, see below:
```
Your WebProtégé password (for user name guest) has been reset to:

 		xxxxx

Please sign in using this new password and then change it after signing in.
```

The user name should be the correct one, not "guest".
