### ISSUE TITLE
Support revision reversion

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#3]
It should be possible to revert to a previous revision.

**Comment by csnyulas** [comment]
I was about to create an issue with the same suggestion. Thinking about the necessary UI change for this, I thought that we could add an additional item to the 'Revision' link menu in the 'Project History' perspective:
![image](https://user-images.githubusercontent.com/2441046/27248076-a4a23c6a-52b3-11e7-9773-8c59500d2c62.png)
Something like "Revert project to revision 3".

**Comment by matthewhorridge** [comment]
Revision reversion is now supported.  Not sure why this issue is still open.  I think you want rollback to a specific revision and discard all revisions after the specified revision.  Is that correct?

**Comment by csnyulas** [comment]
Yes. I was thinking about "Roll back to revision 3", in the sense to reverting all changes that happened after the given revision. I am not sure I would do this by deleting all the subsequent revisions. I would probably create a new revision whose content would be identical to the selected revision.

**Comment by matthewhorridge** [comment]
ok good idea.  I think this deserves a separate issue...

**Comment by csnyulas** [comment]
Sure. I thought this issue was exactly about that, but, based on your earlier comment I realized that it wasn't. I close this issue and I create a new one.
