### ISSUE TITLE
Discussion 'Ok' and 'Cancel' buttons have their link on the frame of the button

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/webprotege#301]
User clicked on discussion icon next to a class in the class hierarchy, discussion pops open, the 'Create new topic' button up top works fine, but the 'Ok' and 'Cancel' at the bottom don't get the hyperlink activated unless you point to the very edge of the button.

**Comment by matthewhorridge** [comment]
Stale issue.  This bit of the UI isn't supported anymore.
