### ISSUE TITLE
Support SWRL in WebProtege

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#311]
This is a request to have similar functionality to SWRLTab in WebProtege. (From the mailing list)

**Comment by matthewhorridge** [comment]
Editing of rules is possible in the OWL Entity Editor Description view.  The predicate of the head of the rule must correspond to the selected class or property.

**Comment by laotao** [comment]
> 

Hi Mat, is there an concrete example showing how to write a rule in OWL Entity Editor Description view?
