### ISSUE TITLE
webprotege 2.6.0 in Eclipse IDE

### ISSUE THREAD

**Issue by merinani** [protegeproject/webprotege#314]
How can I use the latest webprotege 2.6.0 code from GIT Hub or SVN repository in Eclipse IDE? 
Please help to find some documentation or useful links for the same to study the functionalities implemented in webprotege.
Currently I'm working with this following the document on http://protegewiki.stanford.edu/wiki/WebProtegeCompiling

I would like to do the same with the latest webprotege, but cannot find any helpful documents.

Any help would be appreciated.
Thanks!

**Comment by matthewhorridge** [comment]
Hi,

You can find some documentation on how to build webprotege here:

https://github.com/protegeproject/webprotege

There isn’t too much (well, almost no) documentation about the internals, but the project is a pretty standard GWT project layout (separated into client, server and shared packages).  Common GWT patterns (like the dispatch pattern) are used.  You should be able to get a feel from browsing the code - look how portlets interact with the server to get an idea of the calls and how these are handled on the front end and back end.

Cheers,

Matthew


On 24 Nov 2015, at 05:17, merinani <notifications@github.com<mailto:notifications@github.com>> wrote:


How can I use the latest webprotege 2.6.0 code from GIT Hub or SVN repository in Eclipse IDE?
Please help to find some documentation or useful links for the same to study the functionalities implemented in webprotege.
Currently I'm working with this following the document on http://protegewiki.stanford.edu/wiki/WebProtegeCompiling

I would like to do the same with the latest webprotege, but cannot find any helpful documents.

Any help would be appreciated.
Thanks!

**Comment by tudorache** [comment]
Here are the instructions on how to configure Eclipse to work with GWT and Maven:
https://code.google.com/p/google-web-toolkit/wiki/WorkingWithMaven

Closing this issue, please post on the protege-user mailing list for further support.
