### ISSUE TITLE
Trouble with Sign up / login on webprotege 2.5.0

### ISSUE THREAD

**Issue by silke4** [protegeproject/webprotege#315]
Hi, 

I followed the instructions of the WebProtégé Administrator's Guide to install Webprotege 2.5.0.

Everything went fine, I got the initial page of WebProtege on my local server.

I can create a new user account, but I can not log on to protege with any newly created account. Did I miss something?

Setup:
Tomcat Version: Apache Tomcat/7.0.55
JVM Version: 1.7.0_91-b01
OS version SUSE Linux 3.12.48-52.27-default
MongoDB shell version: 2.4.14

Behaviour observed:

In catalina.date.log the following line appears when I create a user:
Dez 03, 2015 10:25:06 AM edu.stanford.smi.protege.server.metaproject.impl.UserImpl <init>
WARNING: User with null name created in the metaproject. Instance: metaproject_Class0

After restarting the tomcat server the user (with its correct user name) and the membership to group 'metaproject_Instance_0' (World) is present in metaproject.pins.

When I use the sign In link a popup-Window appears, where I enter the username and password. Then the message 'Invalid user name or password. Please try again.' pops up. In the catalina.data.out no message appears. Only in localhost_access_log.date.txt some events show up:
 [03/Dec/2015:11:18:39 +0100] "POST /webprotege%2D2.5.0/webprotege/admin HTTP/1.1" 200 14

I also tried to recreate the same user / a user with the same email address. Here Webprotege tells me that it is already present. So, webprotege knows about them, but does not allow me to log into the system. Did I miss something, e.g., altering the metaproject either manually or via stand-alone Protege?

Best regards,
Silke

**Comment by tudorache** [comment]
Might be related to #132.

Did you try to login with the user name or with the email? Please try to login with the user name.

Also, please try to create another user, and see if that works.

As an alternative, please try out  WebProtege 2.6.0 Snapshot, which we plan to release soon:
http://protege.stanford.edu/download/webprotege/candidate/webprotege-2.6.0-SNAPSHOT.war

If the problem still appears, please check the webprotege log (/var/log/tomcat), and report the exception from there.

**Comment by silke4** [comment]
Hi Tania,

thanks for the quick response.

Well I already tried to create different users and log on with their
credentials. I also did not use email addresses to log on, but the user
name. Even with the most simple user and password combination, no login
possible, while metaproject.pins is aware of this user.

I also tried to load webprotege 2.6.0 into tomcat, but it did not even
start in my installation.

catalina.date.log shows the following error:

Dez 04, 2015 9:12:18 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive
/srv/tomcat/webapps/webprotege-2.6.0-SNAPSHOT.war
Dez 04, 2015 9:12:23 AM org.apache.catalina.core.StandardContext
startInternal
SEVERE: Error listenerStart
Dez 04, 2015 9:12:23 AM org.apache.catalina.core.StandardContext
startInternal
SEVERE: Context [/webprotege-2.6.0-SNAPSHOT] startup failed due to previous
errors
Dez 04, 2015 9:12:23 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive
/srv/tomcat/webapps/webprotege-2.6.0-SNAPSHOT.war has finished in 4,686 ms
Dez 04, 2015 9:12:28 AM org.apache.catalina.core.StandardContext
startInternal
SEVERE: Error listenerStart
Dez 04, 2015 9:12:28 AM org.apache.catalina.core.StandardContext
startInternal
SEVERE: Context [/webprotege-2.6.0-SNAPSHOT] startup failed due to previous
errors
Dez 04, 2015 9:12:39 AM org.apache.catalina.core.StandardContext
startInternal

Is there any other logging/debugging possibility for webprotege - either
2.5 or 2.6?

Regards,
Silke

2015-12-03 20:39 GMT+01:00 Tania T. <notifications@github.com>:

**Comment by tudorache** [comment]
@silke4 Please provide the catalina and webprotege logs from /var/logs/tomcat

My assumption is that the metaproject is corrupted somehow. Please try webprotege-2.6.0 in a new data folder (a new metaproject will be created).

This issue is specific for a particular installation, it should be discussed on the mailing list and not as an issue. Let's continue the discussion on the protege-user mailing list. Closing this issue for now.

**Comment by hui001** [comment]
Hi , @tudorache 
   Can I skip the Login? Because I don't know how to create a new user account。。。
   Thanks
