### ISSUE TITLE
Dates displayed in the revisions list are sometimes incorrect

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#316]

**Comment by Veneranda** [comment]
![webprotege date issue](https://cloud.githubusercontent.com/assets/15607865/11670586/d3d45cec-9e56-11e5-827b-a1fbe6ccd396.JPG)

**Comment by Veneranda** [comment]
Hi there.  I was reviewing some revisions made yesterday and noticed that the date appears as 23rd December.  This is clearly incorrect.  Also, it would be nice if the year was also displayed. Rosetta

**Comment by Veneranda** [comment]
The description should read - Date incomplete and incorrect in the WebProtege local mode.

**Comment by Veneranda** [comment]
Brilliant! thank you Matthew
