### ISSUE TITLE
Display full notes

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#317]
Currently it is hard to see the full body of a note, especially if it is longer. The buttons also appear over the text of the message.

Double click on a note should display the full message in a dialog.

Related to #257.

![screenshot - 12092015 - 03 31 08 pm](https://cloud.githubusercontent.com/assets/2709502/11702226/e69d8352-9e89-11e5-86bc-bcacb437890f.png)

**Comment by matthewhorridge** [comment]
N.B.  The buttons only appear over the note on mouse over.

**Comment by matthewhorridge** [comment]
Buttons no longer overlap.  It's now possible/easier to resize the discussions view to show more content.
