### ISSUE TITLE
 Project Feed shows internal identifier instead of display name when entity is deleted

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#323]
When a class is deleted instead of the nice display name, the internal identifier is shown in the Project Feed entry.

![screenshot from 2015-12-09 21 43 54](https://cloud.githubusercontent.com/assets/2441046/11707862/08727102-9ebe-11e5-90b0-e891cb09cbec.png)

**Comment by matthewhorridge** [comment]
This isn't an internal identifier - it's the IRI fragment of the class.  If the label has been deleted then the display name is generated from the fragment and that's how it appears elsewhere in the UI (for example) in the class tree.  I agree, it looks ugly though.  Previous edits don't get renamed like this (at least in the project feed).  I need to think about this a bit more!
