### ISSUE TITLE
The 2.5 release webprotege can't be compile with jdk 1.8

### ISSUE THREAD

**Issue by zhou5852** [protegeproject/webprotege#331]
I have develop some plugins in webprotege.But I use webprotege 2.5,when I build in JDK1.8 ,I found the 
WebProtegeApplicationContext Class can't be initied. The Problem  located in ASM that Spring used can't read the Class and can't be instrumented. May be I should migrate to a new version. Thanks for reading!

**Comment by tudorache** [comment]
For development, please use the latest webprotege code from github.
