### ISSUE TITLE
HTTPS for public instance

### ISSUE THREAD

**Issue by almereyda** [protegeproject/webprotege#341]
The documentation suggests end users to use the live instance at http://webprotege.stanford.edu, despite it is critically insecure: User authentication happens with a custom system, and not, for example, by using third party authentication providers like Google, GitHub, Twitter or others. Additionally, the whole system is only accessible via HTTP.

When you take the responsability to maintain and transmit user credentials, it is of upmost importance to respect the user's privacy by offering HTTPS, better HSTS.

**Comment by matthewhorridge** [comment]
HTTPS is supported on webprotege.stanford.edu now.
