### ISSUE TITLE
404 error when trying to access .pom url

### ISSUE THREAD

**Issue by lchiriac** [protegeproject/webprotege#348]
Trying to build a snapshot and I am getting all sorts of errors, but one of them is thisL

https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/protege/3.5.1.1/protege-3.5.1.1.pom
-----------------
404 - Retrieval of /edu/stanford/protege/protege/3.5.1.1/protege-3.5.1.1.pom from M2Repository(id=snapshots) is forbidden by repository policy SNAPSHOT.
Retrieval of /edu/stanford/protege/protege/3.5.1.1/protege-3.5.1.1.pom from M2Repository(id=snapshots) is forbidden by repository policy SNAPSHOT.
-----------------

Any idea? This is the issue:

ERROR] Failed to execute goal on project webprotege: Could not resolve dependencies for project edu.stanford.protege:webprotege:war:2.6.0-SNAPSHOT: Failed to collect dependencies for [org.hamcrest:hamcrest-all:jar:1.3 (test), org.mockito:mockito-core:jar:1.9.5 (test), junit:junit-dep:jar:4.10 (test), org.jvnet.mock-javamail:mock-javamail:jar:1.9 (test), com.google.gwt:gwt-servlet:jar:2.7.0 (runtime), javax.servlet:jsp-api:jar:2.0 (provided), javax.servlet:servlet-api:jar:2.5 (provided), com.google.gwt:gwt-user:jar:2.7.0 (provided), com.google.guava:guava:jar:18.0 (compile), com.google.guava:guava-gwt:jar:18.0 (compile), com.google.gwt.inject:gin:jar:2.1.2 (compile), com.google.inject:guice:jar:3.0 (compile), com.google.inject.extensions:guice-multibindings:jar:3.0 (compile), org.glassfish:javax.json:jar:1.0.4 (compile), net.tanesha.recaptcha4j:recaptcha4j:jar:0.0.7 (compile), commons-io:commons-io:jar:2.4 (compile), org.apache.httpcomponents:httpclient:jar:4.3.3 (compile), org.apache.httpcomponents:httpmime:jar:4.3 (compile), commons-fileupload:commons-fileupload:jar:1.2 (compile), commons-lang:commons-lang:jar:2.6 (compile), net.sourceforge.owlapi:owlapi-distribution:jar:3.5.0 (compile), net.sourceforge.owlapi:owlapi-gwt:jar:3.4.9 (compile), net.sourceforge.owlapi:binaryowl:jar:1.4.4 (compile), edu.stanford.protege:protege-owlapi-extensions:jar:3.2.4 (compile), org.protege:protege-editor-owl:jar:4.1.0 (compile), org.protege:protege-editor-core-application:jar:4.1.0 (compile), edu.stanford.protege:protege:jar:3.5.1.1 (compile), edu.stanford.protege:bioportal-services-lib:jar:1.0.1 (compile), edu.stanford.protege:notes-api:jar:2.0.0 (compile), javax.mail:mail:jar:1.4.7 (compile), edu.stanford.protege:codemirror-gwt:jar:2.0.0 (compile), com.gwt-ext:gwt-ext:jar:2.0.6 (compile), com.googlecode.gwt-crypto:gwt-crypto:jar:2.3.0 (compile), javax.validation:validation-api:jar:1.0.0.GA (compile), javax.validation:validation-api:jar:sources:1.0.0.GA (test), net.sf.opencsv:opencsv:jar:2.3 (compile), org.springframework.data:spring-data-mongodb:jar:1.6.1.RELEASE (compile), cglib:cglib:jar:3.1 (compile)]: Failed to read artifact descriptor for edu.stanford.protege:protege:jar:3.5.1.1: Could not transfer artifact edu.stanford.protege:protege:pom:3.5.1.1 from/to oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/): Access denied to: https://oss.sonatype.org/content/repositories/snapshots/edu/stanford/protege/protege/3.5.1.1/protege-3.5.1.1.pom , ReasonPhrase:Forbidden. -> [Help 1]

**Comment by tudorache** [comment]
Maven cannot access any of the dependencies. 

protege-3.5.1.1 should be pick up from https://github.com/protegeproject/mvn-repo/tree/master/releases/edu/stanford/protege/protege/3.5.1.1, not from sonatype.

Works fine on other machines.

Closing for now, as it seems like a local configuration issue.
