### ISSUE TITLE
BioPortal Search function appears to be broken

### ISSUE THREAD

**Issue by ebremer** [protegeproject/webprotege#353]
search for "cell" within the WebProtege widget and I get nothing.  I get two hits when I go directly to 
http://bioportal.bioontology.org/search?utf8=%E2%9C%93&query=cell&commit=Search

Other terms like DNA and blood also come up with nothing within the WebProtege context but do yield multiple results on the bioportal web site.

**Comment by matthewhorridge** [comment]
The bioportal search widget is broken due to changes in the BioPortal API.  We need to update it.

**Comment by ebremer** [comment]
Oh, I figured it was something like that.  I just thought I'd try to be helpful and report it.  :)

**Comment by matthewhorridge** [comment]
Thanks! :)

**Comment by tudorache** [comment]
Closing, duplicate of #152.
