### ISSUE TITLE
Issues with webprotege-2.6.0.war

### ISSUE THREAD

**Issue by ernestojimenezruiz** [protegeproject/webprotege#361]
Hi 

I'm trying to install webprotege-2.6.0.war locally. However it does not seem to work. I tried with webprotege-2.5.0.war and it works fine. I located both .war files in the tomcat folder /var/lib/tomcat7/webapps   (I'm using Ubuntu 14.04)

When accessing http://localhost:8080/webprotege-2.5.0/ I get the following log:
"GET /webprotege-2.5.0 HTTP/1.1" 302 -
"POST /webprotege-2.5.0/webprotege/dispatchservice HTTP/1.1" 200 293

However when I access http://localhost:8080/webprotege-2.6.0/ I get the 404 error:
"GET /webprotege-2.6.0 HTTP/1.1" 404 -

Any ideas about the source of the problem?

Many thanks in  advance!

Best
Ernesto

**Comment by matthewhorridge** [comment]
Does anything change if you only have one webprotege web app installed?  In any case, you should not install more than one.

**Comment by ernestojimenezruiz** [comment]
Hi Matthew

I removed version 2.5.0 and something has changed although it doe snot work yet.

The log is now different:
127.0.0.1 - - [16/Jun/2016:10:59:40 +0100] "GET /webprotege-2.6.0/ HTTP/1.1" 404 1003

And instead of getting a blank page I get now the classical "page not found" given by tomcat (see attached).
![error_webprotege2 6 0](https://cloud.githubusercontent.com/assets/15777018/16113122/bd0ed716-33b2-11e6-8185-bbe312d83ce3.png)

**Comment by gzambotti** [comment]
Actually I had the same problem. v2.5.0 works fine but not v.2.6.0. Any suggestions? Thank you.

**Comment by ernestojimenezruiz** [comment]
Hi Giovanni,

Good to know that I'm not the only one.

@matthewhorridge , any updates from your side?

Ernesto

**Comment by matthewhorridge** [comment]
I still need to look into this.  Sorry for the delay.

**Comment by matthewhorridge** [comment]
btw.  I can say that things are working as expected on my machine.

**Comment by ChristophB** [comment]
Hi Ernesto,

i managed to install v2.6.0 without problems.
The only difference to your installation is that my webprotege folder in webapps is named "webprotege" not "webprotege-2.6.0".

Did you specify the params "data.directory" and "application.host"?
What is the status of v2.6.0 in tomcat manager?

Christoph

**Comment by matthewhorridge** [comment]
webprotege-2.6.0 works for me.  I'm using tomcat 8.0.14.

**Comment by ChristophB** [comment]
I'm on tomcat 8.0.35... maybe there are compatibility problems with tomcat7?

**Comment by ernestojimenezruiz** [comment]
Hi Christoph and Matthew

It seems it was an incompatibility with tomcat 7. Using now tomcat 8 and it works.

Many thanks for your help!

Best
Ernesto

**Comment by csnyulas** [comment]
It would be still good to know why it is not working in tomcat 7. Not everybody has the liberty to install tomcat 8 on their servers. If this is a requirement to run WebProtege, we should make it clear, and it would be also nice to be able to give an explanation to them for why they need it (maybe they can convince their IT department to upgrade their tomcat).

**Comment by tudorache** [comment]
It does work on tomcat7. tomcat7 on Ubuntu 14.04 uses by default Open Java 7 (even if java 8 is installed), and webprotege is compiled for Java 8, so there is an error thrown in the tomcat logs, like this:

```
Jul 08, 2016 10:29:17 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class edu.stanford.bmir.protege.web.server.WebProtegeInitializer
java.lang.UnsupportedClassVersionError: edu/stanford/bmir/protege/web/server/WebProtegeInitializer : Unsupported major.minor version 52.0 (unable to load class edu.stanford.bmir.protege.web.server.WebProtegeInitializer)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2948)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1208)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1688)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:529)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:511)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:139)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4925)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5504)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

This error causes webprotege to not start. The solution is to configure tomcat7 to use Java 8. The easiest way is to edit the file /etc/default/tomcat7 and edit JAVA_HOME to point to a Java 8 JDK directory.

To test which version of java tomcat is using, type in a terminal:
```ps -ef | grep java```

(Before the changing JAVA_HOME, it will probably show java 7). After changing JAVA_HOME, it should show java 8, something like:

```
tania@l:/usr/lib/jvm/java-8-oracle$ ps -ef | grep tomcat
tomcat7   8207  2617 16 14:05 ?        00:00:22 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/var/lib/tomcat7/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC -Dwebprotege.data.directory=/work/webprotege/webprotege2/data/ -Dwebprotege.application.host=localhost:8080 -Djava.endorsed.dirs=/usr/share/tomcat7/endorsed -classpath /usr/share/tomcat7/bin/bootstrap.jar:/usr/share/tomcat7/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat7 -Dcatalina.home=/usr/share/tomcat7 -Djava.io.tmpdir=/tmp/tomcat7-tomcat7-tmp org.apache.catalina.startup.Bootstrap start
```

Here is how to set Java 8 for tomcat7 (more details, if needed):
http://askubuntu.com/questions/154953/specify-jdk-for-tomcat7

And here are more details on the error:
http://stackoverflow.com/questions/24504211/tomcat-7-with-java-8-on-windows-and-linux
