### ISSUE TITLE
Support the moderation of user account creation

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#362]
From the mailing list.

---

I installed webprotege 2.6 and everythink is ok but the possibility to create an account by client without admin control (moderate) is a problem for me.
How can I change this ? I would like to accept or refuse (moderate) the account creation or suspend it, do creation by myself and then give passwords to my users. I succeeded in creating new user with
metaproject.ppt.

I have seen in the documentation the "server.allow.create.users=true/false" directive that is exactly what I needed !!

**Comment by matthewhorridge** [comment]
The admin can now disable/enable account creation in WebProtege as they wish.  We still don't support account moderation though.

**Comment by matthewhorridge** [comment]
Now supported in WebProtege 3.0.0.
