### ISSUE TITLE
com.google.gwt.user.client.rpc.SerializationException on Ubuntu

### ISSUE THREAD

**Issue by DaliMidou** [protegeproject/webprotege#363]
Hi,
I built WebProtege for use on local host. The same war file works fine on Windows but on Ubuntu I get the following exception:
com.google.gwt.user.client.rpc.SerializationException: Type 'edu.stanford.bmir.protege.web.shared.auth.AuthenticationResponse' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer.For security purposes, this type will not be serialized.: instance = SUCCESS

I used the same versions of softwares on Windows and Ubuntu (java 1.8.0_91, tomcat 8.0.35, mongodb 3.2).

**Comment by tudorache** [comment]
Likely the same as #361. Please try the solution at the end of the thread, and post back.

**Comment by matthewhorridge** [comment]
Closing issue due to lack of response from original poster.
