### ISSUE TITLE
WebProtege parses strings containing IRIs as IRIs

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#365]
For example,

"This is a test. http://test.com/test"

would be parsed as an IRI.  This leads to invalid output.

**Comment by matthewhorridge** [comment]
The pattern for testing whether something is an IRI is incorrect:

```
/(\w+):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/
```

**Comment by jjkoehorst** [comment]
Any progress on this? We have web Uris in comment like sections for our parsers but this is now currently broken by webprotege. We can work around it with using urls that are 99% according to http protocol like: http$//here.com such that it is not picked up by the parser but this needs then to be explained to each editor.

**Comment by matthewhorridge** [comment]
It's fixed, but not synced with this repo yet.  The fix will be available in the new year in WebProtege 3.
