### ISSUE TITLE
webprotege.stanford.edu not available :-(((

### ISSUE THREAD

**Issue by matuskalas** [protegeproject/webprotege#370]
Hey, the http://webprotege.stanford.edu is unavailable. I'm getting 502 Bad gateway:

### Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request [_GET /_](http://webprotege.stanford.edu/).

Reason: **Error reading from remote server**

Can it please be fixed?
I'm using WebProtégé for visualizing the EDAM ontology during the development of its new versions.

Thanks a million times!

**Comment by csnyulas** [comment]
We are looking into this.

**Comment by matuskalas** [comment]
Thank you so much, I'll be extremely useful if I can use WebProtégé again very soon!

Do you need any more details, or can you reproduce it?

**Comment by csnyulas** [comment]
Yes, it should work now. I will close this issue. 
Apologies for the inconvenience cause by the outage!

**Comment by matuskalas** [comment]
Thank you so much for making it work again!
