### ISSUE TITLE
Show Project name in the ontology view

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#372]
When editing a project, it would be useful to see the name of the project (before it used to be in the tab title).

**Comment by tudorache** [comment]
Don't remember what this was.

**Comment by csnyulas** [comment]
I think the idea was to show the Project name in the browser's header, by setting the title of the web page, as now (in WebProtege Beta) there is no indication about which project one is currently editing. This has been solved in WebProtégé 3.0, though. At least the project's name is displayed at the top of the page, even if not in the page title.

**Comment by matthewhorridge** [comment]
Yes, it's displayed at the top of the page.  Only the application name is displayed in the title bar.  Safari doesn't even show the title bar....

**Comment by csnyulas** [comment]
Could we include the project name in the page title (so that it is easier to identify the right ontology, when working with multiple ontologies in WebProtégé). This would be especially useful now that in version 3.0 each browser tab can be used to the editing of a single ontology at a time.

**Comment by matthewhorridge** [comment]
Opened a [new issue for the Window Title](https://github.com/protegeproject/webprotege/issues/416) rather than reusing this issue, which is for something else.
