### ISSUE TITLE
@ in comment or other field pushes it to language

### ISSUE THREAD

**Issue by jjkoehorst** [protegeproject/webprotege#374]
When using the @ symbol in various locations the parser thinks this is a language symbol and automatically pushes everything behind it into the language variable. I can currently escape it by either already filling in something in the language or by using \@ but is there a way to not let the parser my comments?

**Comment by matthewhorridge** [comment]
This has been fixed for the new version of WebProtege (3.0.0), which will hopefully be available early next year.
