### ISSUE TITLE
Adding a data property with float value to individual causes error

### ISSUE THREAD

**Issue by ChristophB** [protegeproject/webprotege#379]
* When i want to add a data property to an individual with a float as value i get the following error:
`could not get type signature for class uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplFloat`

* Doing the same thing in the OWL Entity Description Editor works but prevents the individual from loading. This error occurs in the log file:
`com.google.gwt.user.client.rpc.SerializationException: Type 'uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplFloat' was not included in the set of types which can be serialized by this SerializationPolicy or its Class object could not be loaded. For security purposes, this type will not be serialized.: instance = "-2.0"^^xsd:float`

**Comment by matthewhorridge** [comment]
Thanks for the report this has already been fixed for the next version of WebProtege.  In any case, I recommend that you use xsd:decimal over xsd:float as xsd:decimal is in the OWL 2 Datatype Map and xsd:float is not.

**Comment by matthewhorridge** [comment]
This version of WebProtege is now available at webprotege.stanford.edu.
