### ISSUE TITLE
Adding a new portlet to the view does not initialize its content

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#383]
For example if I add the `Class Editor` portlet to my tab, I see this 
![wp3 0_class_editor_portlet_new](https://cloud.githubusercontent.com/assets/2441046/24273274/a129ce8a-0fde-11e7-9549-6eaafb27fff5.png)
instead of this
![wp3 0_class_editor_portlet](https://cloud.githubusercontent.com/assets/2441046/24273297/c4b40f00-0fde-11e7-9b7e-57b53bceefd7.png)
Observe the missing fields, where I could start filling in content.

Another example: if we add the `OWL Entity Descriptor` portlet to a tab, it will be empty, and its content will not be filled until we change the selection in the controlling portlet (e.g. the class hierarchy).
I see this:
![wp3 0_owl_entity_descriptor_editor_portlet_new](https://cloud.githubusercontent.com/assets/2441046/24273445/a028f938-0fdf-11e7-8da4-23e82207f9c4.png)
while in another portlet of the same type, which was added earlier (before the selection changed), I see this:
![wp3 0_owl_entity_descriptor_editor_portlet](https://cloud.githubusercontent.com/assets/2441046/24273462/b707d49e-0fdf-11e7-8809-aef889abee5e.png)
Note that in this case not even the portlet's title is the same.

**Comment by matthewhorridge** [comment]
This was fixed at some point for the Editor view.  I've split the issues with the other views off into a separate GH issue.
