### ISSUE TITLE
Ontology content does not load in WebProtege when using FireFox

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#386]
This is what I see when I load an ontology in FireFox (v. 52.0.1 (64-bit), on Ubuntu)

![wp3 0_no_ontology_content_in_ff](https://cloud.githubusercontent.com/assets/2441046/24273643/a3c934ee-0fe0-11e7-8ec5-d221a855bc8e.png)

**Comment by matthewhorridge** [comment]
Fixed.
