### ISSUE TITLE
Webprotege doesn't load ontologies

### ISSUE THREAD

**Issue by matuskalas** [protegeproject/webprotege#391]
Hey, while it worked fine yesterday, today none of us can open an ontology in Webprotege. The listing and logging-in is fine, but after clicking on an ontology, it gets stuck in the "Loading, please wait" state.
It'd be super cool to get working asap, as we're doing some collaborative dev now.

EDAM-bioimaging (live version), BISE core ontology

Various OSs, various browsers

Thanks!

**Comment by matthewhorridge** [comment]
Hi, sorry for this inconvenience!  Please can you try to access webprotege now?

**Comment by matuskalas** [comment]
Works now, thanks a lot!

A pity we couldn't use it yesterday, as we had a whole-day hackathon :-( Webprotégé is an extremely useful application for us, cannot live without it! :+1:
