### ISSUE TITLE
OntoGraf

### ISSUE THREAD

**Issue by Veneranda** [protegeproject/webprotege#392]
I have been unable to use OntoGraf to show the individuals for a class. Is the visualization restricted only to the is-a class hierarchy relationships?

**Comment by hui001** [comment]
Hi~
  Is there a OntoGraf for webprotege? Could you please tell me where it is. Thank you ! @Veneranda

**Comment by matthewhorridge** [comment]
Please use the Protege mailing list for these discussions. Thanks.
