### ISSUE TITLE
Can't create my portlet

### ISSUE THREAD

**Issue by gdutcaleb** [protegeproject/webprotege#398]
Hi,
    I followed this tutorial: https://protegewiki.stanford.edu/wiki/WebProtegeImplementationGuide (1.ceate 
subclass of **edu.stanford.bmir.protege.web.client.ui.portlet.AbstractOWLEntityPortlet**;2.Implement the initialize() method ;3.add portlet to **edu.stanford.bmir.protege.web.client.ui.generated.UIFactory** ) ,but my portlet can't work,it go blank,what did I miss?

**Comment by matthewhorridge** [comment]
If you're working with the latest master branch then things have changed considerably and those instructions no longer apply.  We need to update the documentation....
