### ISSUE TITLE
Range type disappears after refresh on DataProperty In WebProtege 3.0

### ISSUE THREAD

**Issue by tharakv** [protegeproject/webprotege#401]
Issue: Range type is disappear after refresh the DataPropety in Web Protege 3.0 
Expectation:  Range type should show in screen after adding field name in   DataPropety in Web Protege 3.0 
Step1: Add “id” as data property to class and assign range as “xsd:long” or “xsd:string”
![image](https://cloud.githubusercontent.com/assets/28535175/25807436/d4dbc034-33d4-11e7-841d-8e98bac5d858.png)

Step2: Now , refresh the data property and surprisingly you could see below range type will disappear.
But you could see the Range type in graph stored in disk.
![image](https://cloud.githubusercontent.com/assets/28535175/25807456/e48c1b14-33d4-11e7-8110-ac0887a527e0.png)

Issue: Range type is disappear after refer the dataproperty.
Expectation:  Range type should show in screen after adding field name in  data property.

Please refer the attached document for the same.

Regards!
Tharak
[Web Protégé 3.0 _ DataProperty Range type issue.docx](https://github.com/protegeproject/webprotege/files/983664/Web.Protege.3.0._.DataProperty.Range.type.issue.docx)

**Comment by matthewhorridge** [comment]
Thanks for the bug report.  I can reproduce this.  I'll take a look at it asap.
