### ISSUE TITLE
Visualize and add namespaces

### ISSUE THREAD

**Issue by nvitucci** [protegeproject/webprotege#413]
An interface for visualizing/adding/updating namespaces (like the "Ontologies Prefixes" panel in Protégé) would be very useful. This would ease the pain of creating entities with a different base IRI, since built-in prefixes (e.g. `skos`) can already be used in this way.

**Comment by matthewhorridge** [comment]
Makes sense!

**Comment by nvitucci** [comment]
Thanks for the feedback, Matthew. Any idea about the implementation time for this?

**Comment by matthewhorridge** [comment]
I'll try and do it this month, but I can't promise anything! :)

**Comment by Jefwillems** [comment]
any update on this issue? We need this feature as well.

**Comment by matthewhorridge** [comment]
It's work in progress now.  Details here:

https://github.com/protegeproject/webprotege/tree/issue-413

**Comment by matthewhorridge** [comment]
Implemented and merged into master
