### ISSUE TITLE
Export does not work on webprotege.stanford.edu

### ISSUE THREAD

**Issue by muichkine** [protegeproject/webprotege#414]
Whatever format one chooses, the request never success.

**Comment by matthewhorridge** [comment]
Sorry for these problems.  Please can you retry it now?

**Comment by muichkine** [comment]
It works like a charm. Thank you! :)

BW it's still unclear what are the term of use for webprotégé. I understand the Licence for a setup on my own instance, but what about the hosted version. To what point can you insure that data is safe and that the service will remain for the forseeable future ?

Thank you.

**Comment by matthewhorridge** [comment]
You're welcome.  You can find general terms of use [here](http://webprotege.stanford.edu/html/termsofuse.html).  In terms of keeping data safe, we perform nightly backups of all data stored in WebProtege.  In terms of continuation, the project is funded for another 3.5 years so you can expect it to be around for at least that long, if not longer.

**Comment by muichkine** [comment]
Thank you
