### ISSUE TITLE
Cancel and OK buttons are too close to each other

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#419]
There should be some space between the `Cancel` and `OK` buttons in the "Change Password" and "Change Email Address" dialogs. Having then stick to each other looks strange:
![image](https://user-images.githubusercontent.com/2441046/32919273-082fd618-cada-11e7-9b5b-86d41738176f.png)

Observed in:
- Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Win7
- IE11 on Win7
- Chrom 62 on Ubuntu
- FF 56 on Ubuntu

Also, make the `Cancel` button's background color a bit darker, even in inactive mode. Currently the button can be barely seen in IE11 and FF56 .

![image](https://user-images.githubusercontent.com/2441046/32920138-1a239d7a-cadd-11e7-9ec5-4c49eec48659.png)

**Comment by csnyulas** [comment]
This seems to be a problem with all the dialogs, eg. "Create Class", "Delete Class", "Revert Changes", etc.

**Comment by matthewhorridge** [comment]
Fixed

**Comment by csnyulas** [comment]
I can confirm that the spacing btw. buttons and `cancel` button's color looks good on all browsers and OSs I've tested (FF and Chrome on Ubuntu, and FF, IE11, Chrome and Opera in Win7).

I would just mention that the label of the buttons is not quite vertically centered in FF, Chrome and Opera (in IE11 seems to be fine). The shift is most obvious in FF, where the label is significantly lower than the center:
![image](https://user-images.githubusercontent.com/2441046/32987936-cb41d60e-ccad-11e7-9b3a-1a6fc2492cd8.png)

The shift in Chrome and Opera is just a tiny bit upwards, which is barely noticeable, and not very unpleasant to the eyes:
![image](https://user-images.githubusercontent.com/2441046/32987947-011e7bb0-ccae-11e7-80d5-a549c37cfabe.png)

None of these problems is critical, but feel free to open a new issue for this, if you think it is worth fixing it.
