### ISSUE TITLE
Reverting changes in the history view should refresh the list of changes

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#420]
The `Refresh` button in the `Project History` view is too faint. I could not find it at first (and second and maybe third try), despite explicitly looking for a mechanism to refresh the content of the project history. It needs to be more visible. Maybe even add an icon (which suggests reload) to it.

**Comment by matthewhorridge** [comment]
Possibly because it was greyed out.... it's only enabled if there have been changes since the last refresh.

**Comment by csnyulas** [comment]
That must be it!
I was wondering why don't we do an automatic refresh if someone reverts a certain revision. It is a bit strange that you do an action with the change history and you don't see any immediate effect on it.

**Comment by matthewhorridge** [comment]
Ah right.  Makes sense.
