### ISSUE TITLE
Icon and project name are not aligned in the title bar

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#421]
1. The Protege icon and the word "Projects" on the home screen (or the name of the project when a project is open) are not center aligned vertically. The icon seems shoved in the corner, without any padding around it (which looks bad on itself), while the "Projects" word (or the name of the project) has more space above it than below it in the title bar.
2. The font size of the "Projects" word (or the name of the project) seems too big. Way bigger than anything else on the screen. Maybe this won't be an issue if step 1) is nicely done. However, decreasing the font size a few pixels (and maybe using other mechanisms to emphasize it) would not hurt.

**Comment by matthewhorridge** [comment]
I think this is fixed now.  It looks ok to me in the various browsers, but I need confirmation for you @csnyulas.

**Comment by csnyulas** [comment]
I can confirm that the spacing btw. buttons and `cancel` button's color looks good on all browsers and OSs I've tested (FF and Chrome on Ubuntu, and FF, IE11, Chrome and Opera in Win7). So, I think we can close this issue.

I would just mention that the label of the buttons is not quite vertically centered in FF, Chrome and Opera (in IE11 seems to be fine). The shift is most obvious in FF, where the label is significantly lower than the center:
![image](https://user-images.githubusercontent.com/2441046/32987936-cb41d60e-ccad-11e7-9b3a-1a6fc2492cd8.png)

The shift in Chrome and Opera is just a tiny bit upwards, which is barely noticeable, and not very unpleasant to the eyes:
![image](https://user-images.githubusercontent.com/2441046/32987947-011e7bb0-ccae-11e7-80d5-a549c37cfabe.png)

None of these problems is critical, but feel free to open a new issue for this, if you think it is worth fixing it.
