### ISSUE TITLE
"Commented Entities" view does not refresh after new comments have been added

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#423]
Since the "Commented Entities" view does not automatically update its content after new comments have been added, there should be a "Refresh button" to allow the user to see the latest comments. At the moment the only way to see newly added comments in the "Commented Entities" view (AFAICT) is to change the sort order, which is a strange way to do it.

**Comment by matthewhorridge** [comment]
Sounds like a bug.  It should refresh itself.

**Comment by csnyulas** [comment]
Now, the "Commented Entities" portlet does refresh automatically (after a short delay), but only if the comment was added to an entity that did not yet have any comments (i.e. starting a new thread on an entity that already had some comment, would not automatically refresh the view) and only if the "Sort by Entity" option is selected (i.e. does not work if the "Sort by Last Updates" option is selected). 

Ideally this should be fixed (or add a "refresh" button :) ), so I reopen the issue.
