### ISSUE TITLE
Problem with Drag and Drop: Grabbing tree node does not work properly

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#430]
This is one of several issues with the drag&drop functionality in the newly implemented class tree in WP 3.0:

The selection of the element to be dragged is not very consistent. For example, the selection of a class in the class tree (in case I want its details displayed in other portlets) works anywhere. I click anywhere on a given row in the tree (on the label, on the icon, before or after the label, on the comment icon, etc). But the same is not true if I want to drag it. In FF I can drag it only if I "grab" it from the icon (nothing else works), while in Chrome I can "grab" it from anywhere with the exception of the label. Ideally the "grabbing" should work from anywhere on the row, just like the simple selection.

**Comment by matthewhorridge** [comment]
Fixed.  The tree was set up to allow selection of text in nodes, but it seems like this interferes with drag starts in FireFox.  I've disabled this.
