### ISSUE TITLE
Problem with Drag and Drop: Messy highlighting in Firefox

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#431]
This is one of several issues with the drag&drop functionality in the newly implemented class tree in WP 3.0:
When I try to drag and drop a class in Firefox, sometimes several other classes get highlighted in dark blue background, like in the screen shot below:
![image](https://user-images.githubusercontent.com/2441046/33853731-d788f42e-de73-11e7-972a-def0e9e4cf16.png)

These highlightings won't disappear easily.

Hovering over this highlighting makes the text unreadable (see the class Mango below, as an example):

![screenshot_wp3_dnd_highlight](https://user-images.githubusercontent.com/2441046/33854062-31e32f2e-de75-11e7-8e11-8f2f10665a4d.png)

Sometimes even such a mess can happen:
![image](https://user-images.githubusercontent.com/2441046/33853849-554217ec-de74-11e7-987c-ad933d636b22.png)

This seems to be Firefox specific. Tested on latest FF 57.0.1. in Ubuntu

**Comment by matthewhorridge** [comment]
Reproducible on FireFox.  Works fine in Safari and Chrome.

**Comment by matthewhorridge** [comment]
After looking into this some more, there are various quirks with FireFox and HTML5 drag and drop.  The problem above was caused by drag leave events and then drag enter events being fired whilst hovering over text nodes.  Fixed/worked around for next build.

**Comment by matthewhorridge** [comment]
Fixed.
