### ISSUE TITLE
Hierarchy Refresh only refreshes the view and not the underlying data structures

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#437]
There are many situations when refreshing the class tree (and I assume the property tree as well) using the "Refresh Tree" menu option does not work as expected, for example:
- when the `rdfs:label` (used as the browser text) is changed (#433), or 
- often when classes have their superclasses changed either by drag-and-drop (#435) or by deleting or modifying superclasses in the Entity Editor (#436), or
- dragging ad dropping a watched class (#432), etc.

All these suggest that the the "Refresh Tree" does not do a full reload of the content, which may be necessary to present an accurate state of the class hierarchy tree.

**Comment by matthewhorridge** [comment]
The current refresh does a reload of the view only i.e. not the underlying tree or graph structure.  I'll change this to do a "deeper" refresh.
