### ISSUE TITLE
encoder problem

### ISSUE THREAD

**Issue by sshmyeclipse** [protegeproject/webprotege#443]
hi,when I used webprotege to edit Chinese words, the Class description for Chinese Words were encoded. For example the Display name is 电池，but the IRI is http://test/ontologies/example/tdb#%E7%94%B5%E6%B1%A0
Can webprotege show the IRI http://test/ontologies/example/tdb#电池？
Thanks!

**Comment by matthewhorridge** [comment]
Duplicate of https://github.com/protegeproject/webprotege/issues/442  (fixed for the next version of WebProtege).
