### ISSUE TITLE
Highlight in the class tree the classes that have comments added

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#444]
It would be cool if we could show in the class hierarchy tree a comment sign for the classes that have (open) discussion threads. This could be presented with a discrete little icon, similar to the "Watch" icon. Ideally this feature could be switched on/off through a setting that the user can control. This only makes sense if we can find a very efficient way to calculate comments associated to classes. 

A similar feature was found very useful by the users in WP 1.0 and iCAT:

![image](https://user-images.githubusercontent.com/2441046/34871571-0576385a-f743-11e7-8155-080d71a72046.png)

**Comment by matthewhorridge** [comment]
Icons for direct comments are already shown along with comments counts.  We don't display aggregate indirect comments counts for asserted subclasses anymore.  Instead, users can access and browse comments/issues directly in the Commented Entities view, which is shown on the Comments tab by default.  This strikes me as being more user friendly and efficient than hunting for comments by drilling down the class hierarchy.

**Comment by csnyulas** [comment]
Sounds good.
