### ISSUE TITLE
Helvetica Neue font weight too thin

### ISSUE THREAD

**Issue by khawkins98** [protegeproject/webprotege#456]
A request for a small change. For those users that have Helvetica Neue thin installed on their machines, the text is very hard to read as `body, input, textarea, keygen, select, button` elements all have the 300 weight:

![image](https://user-images.githubusercontent.com/928100/36945269-3c8b5900-1fa3-11e8-8081-bd8e3468b3c3.png)

A 400 weight is far more legible:

![image](https://user-images.githubusercontent.com/928100/36945279-4d0dff6c-1fa3-11e8-9f71-f6d10737bfa2.png)

I couldn't locate the source for the CSS, but the change should be quite simple (I'd think):

http://webprotege.stanford.edu/css/WebProtege.css at line 30:
```
body, input, textarea, keygen, select, button {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-weight: 400;
    color: #505050;
    font-size: 12px;
}
```

**Comment by matthewhorridge** [comment]
@khawkins98 yeah, I noticed it was looking a bit thin on Chrome, but thought it was still legible.  Will take a look at this.

**Comment by khawkins98** [comment]
👍 Thanks for the edit. Imagine it's only an issue for the small portion of users that have Helvetica Neue Lt installed.

**Comment by matthewhorridge** [comment]
You're welcome @khawkins98.
