### ISSUE TITLE
Add support for tags for entities

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#458]
A bit like GitHub labels but tags for terms (so as not to be confused with rdfs:labels).

**Comment by csnyulas** [comment]
The idea being to filter terms based on tags?

**Comment by matthewhorridge** [comment]
Sure

**Comment by matthewhorridge** [comment]
Could actually be stored as annotations.... or elsewhere so as not to pollute the ontology

**Comment by matthewhorridge** [comment]
Implemented and merged into master.
