### ISSUE TITLE
Unable to login to https://webprotege.stanford.edu/

### ISSUE THREAD

**Issue by samdus** [protegeproject/webprotege#476]
Hi,

When I try to login to https://webprotege.stanford.edu/ the page gets this answer :  

![image](https://user-images.githubusercontent.com/8702138/38470542-697342b6-3b32-11e8-9e3c-27f6bc1d6844.png)

But it seems to ignore the result, so I can't login. 
I tried in Chrome and IE and the result is the same.

**Comment by matthewhorridge** [comment]
Closing due to no response – assuming things work now.
