### ISSUE TITLE
Webprotégé displays Id instead of label

### ISSUE THREAD

**Issue by muichkine** [protegeproject/webprotege#484]
Since a couploe of weeks, webprotege.standford.eu displays like this:

![image](https://user-images.githubusercontent.com/2428966/38978071-930f4110-43b6-11e8-99f5-12ad24f10867.png)

even though the nodes with displayed ID do have a label

**Comment by matthewhorridge** [comment]
Fixed in master.  webprotege.stanford.edu will be updated shortly.

**Comment by matthewhorridge** [comment]
@muichkine, just to let you know, I've now updated webprotege.stanford.edu

**Comment by muichkine** [comment]
Thank you matthew
