### ISSUE TITLE
can resolve PortletFactoryGenerated

### ISSUE THREAD

**Issue by nickyyyyy** [protegeproject/webprotege#486]
can resolve PortletFactoryGenerated
why？

**Comment by matthewhorridge** [comment]
Can you provide a few more details about what you're doing?  Also, where does the error message come from?

**Comment by nickyyyyy** [comment]
I have down the code  and import to the IDEA，when i bulid the project，there are some error。
This is the picture
![default](https://user-images.githubusercontent.com/13178048/40153565-fafa5dde-59bc-11e8-8608-9089ec95769f.png)

**Comment by matthewhorridge** [comment]
Please use maven to compile the project initially.  This will cause several source files to be generated and these include the files that you identify here.

**Comment by nickyyyyy** [comment]
oh！ Thanks , i have solve the problem. But , there is no  'sign up' button. Why?
I am sorry, i am not good at english.

**Comment by csnyulas** [comment]
You have to enable account creation in your global application settings as described below:
https://github.com/protegeproject/webprotege/wiki/WebProt%C3%A9g%C3%A9-3.0.0-Installation#edit-the-webprot%C3%A9g%C3%A9-settings
