### ISSUE TITLE
Add new conditions to query view

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#514]
Here are some examples of more conditions that could be useful to define queries or tags:
1. Is class
2. Is property
3. Is individual
4. Has tag
5. Has comment attached (by/before/after/contains/matches regex/doesn't match regex)
6. Was modified (by/before/after)

Notes:
1-3 would allow filtering by type of entity. Could be interesting in combination with other conditions, or in queries. 1. and 3. can already be achieved with "Is a (non-direct) subclass of" and "Is a (non-direct) instance of" owl:Thing - which is a bit more work but maybe it is OK to keep it like that to reduce the number of options. Maybe adding an "Is subproperty of" option would fulfill list item 2.
4. Can be used to further filter tags. E.g. Give me all entities which have label "French label" and that are not deprecated. Circular references should not be allowed
6. may be very difficult

**Comment by matthewhorridge** [comment]
The first four are already possible see "Type is one of"

**Comment by csnyulas** [comment]
Oh, this is cool!
That's the first 3 only, though. The Tag is not one of the types.
Related item 4, of course one can achieve the same thing even now, by combining multiple conditions in the same rule, but this would allow much easier combination of tags  without the need to repeat complex conditions.

**Comment by csnyulas** [comment]
Was split in separate issues (see references above). I am closing this now, but if there will be additional issues created related to this topic, we should refer back to this.
