### ISSUE TITLE
Classes with missing display names are not resolved properly

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#524]
When clicking on a class with missing display name in the query results, WebProtege always jumps to the same class in the class tree in the "Classes" tab. 

For example, in the following situation, if I click on any of the six results (representing 6 different classes with missing display labels), WebProtege will always bring me to the same class in the class tree in the "Classes" tab.
![image](https://user-images.githubusercontent.com/2441046/44756596-372ea480-aae0-11e8-84b9-8f30b51f12a2.png)

**Comment by csnyulas** [comment]
Worth checking if this isn't a universal problem, with any group of multiple classes sharing the same display name.

**Comment by matthewhorridge** [comment]
This isn't to do with missing names, or shared names, as far as I can tell.  It's more to do with preference changes in display name.
