### ISSUE TITLE
Support initial display name settings for new ontologies

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#536]
When creating a new project, the display name settings have no property and/or language preferences set. As a result of this, newly created classes do not show any meaningful name (only the local names from the auto-generated IRIs). We should somehow "pick up" what the user may want to use as the default display name from the annotation properties and language tags he or she uses to create the first classes in the ontology. This is related to #531 (or at least the solution could be the same) but is more critical, as it makes the initial use of WebProtege unintuitive.

**Comment by matthewhorridge** [comment]
The default is rdfs:label without a language tag (and a UUID for the IRI)

**Comment by matthewhorridge** [comment]
Now on the "Create Project" form
