### ISSUE TITLE
Add new conditions to query view: filter by object/data property restrictions

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#542]
It would be cool to be able to filter classes not only by annotation property values, but also by certain type of logical axioms, especially those that involve object or data properties.
 
Related to #514.

**Comment by laotao** [comment]
I need these features, too, especially the "hasObjectProperty exact Value" and "hasDatatypeProperty exact Value" restrictions.

**Comment by matthewhorridge** [comment]
Implemented in https://github.com/protegeproject/webprotege/commit/181a05fc0d57eba6293240a333a165d5ab1983b5
