### ISSUE TITLE
Individuals by Class View: Jump to parent could also allow selection between multiple parents

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#552]
Right now clicking on the "Jump to child" or "Jump to sibling" buttons, will show a list of children/siblings that one can choose from (see screen shot below). The same should happen also if one clicks on the "Jump to parent" button for a class that has multiple parents. Right now WebProtege would jump up to one of the parents, without giving the user a chance to choose.

![image](https://user-images.githubusercontent.com/2441046/45914046-3a256800-bdf4-11e8-9030-3b565c17f6ff.png)

On a related note:

a) If a class has only one child, consider jumping to it automatically when user click on "Jump to child" button, without presenting the list with one element, requesting an additional click.

![image](https://user-images.githubusercontent.com/2441046/45914224-c6388f00-bdf6-11e8-8e8c-6031eb969877.png)

b) I observed that the generation of the list of siblings when user clicks on "Jump to sibling" button, takes into account multiple parents, and generates the list of siblings from all parents. This is really great! I would suggest that the currently selected class would be removed from the list of the siblings, because a class is not a sibling of itself. This may be even more important if there are multiple parents, in which case the current class is listed several times (ones for each parent).

![image](https://user-images.githubusercontent.com/2441046/45914251-19124680-bdf7-11e8-9053-c164d75d2e5c.png)

c) Closely related to the previous point: if a class does not have any siblings (currently it is the only class listed in the list of siblings), the "Jump to sibling" button should be disabled.

![image](https://user-images.githubusercontent.com/2441046/45914237-f41dd380-bdf6-11e8-88b4-8748fd3e5f78.png)

**Comment by csnyulas** [comment]
I reopen this, as it seems to me that there is still a tiny problem left.

If I have this hierarchy, with _Apple_  having two superclasses (_Fruit_ and _Computer_ - just for the sake of the argument, I would never do an ontology like this in real life :) )
![image](https://user-images.githubusercontent.com/2441046/45981716-dcb73400-c00a-11e8-98a3-63340dfc86f1.png)

If I go to "Jump to parent" I see only one listed:
![image](https://user-images.githubusercontent.com/2441046/45981747-fb1d2f80-c00a-11e8-8c7f-49a3780f22f3.png)

As I suggested in the original issue description, If there is only one parent, the jump could automatically happen, to save an extra click. For example, in the case of _Fruit_, showing the _owl:Thing_, which is the only parent, is unnecessary:
![image](https://user-images.githubusercontent.com/2441046/45981858-59e2a900-c00b-11e8-8bef-f673a2931376.png)

However if you have multiple parents, all of them should be listed.

**Comment by csnyulas** [comment]
On the other hand, I see that suggestion b) was implemented. Thank you! This is really cool!
In this case, however, I would recommend implementing also c), because right now, if a class does not have any siblings, the list presented for "Jump to sibling" is empty.
![image](https://user-images.githubusercontent.com/2441046/45982186-9f53a600-c00c-11e8-8ebb-9e6eafdaeee5.png)

**Comment by csnyulas** [comment]
Similarly to suggestions a) and d) we could also consider the following:

e) If there is only one sibling (when accounting for all the parents) for a class, the jump could automatically happen when one clicks on the "Jump to sibling" button. This would save an extra click. This is may be an over-optimization, which may or may not pay off in terms of improved usability. So, consider this only as an idea up for consideration, rather than a strong suggestion.

**Comment by matthewhorridge** [comment]
I prefer to show the popup, even if there is just one item in it for consistency.  This also lets users preview the item and decided wether they really want to jump to it.

**Comment by csnyulas** [comment]
I agree with your comment @matthewhorridge. Which means you rather not do a), d) and e).
Besides the main topic, you also fixed b).
Would you consider c) (the disabling of the "Jump to sibling" button, if there are no siblings), which would be consistent with the behavior of the other buttons in similar circumstances.
Thanks.

**Comment by matthewhorridge** [comment]
@csnyulas please could you open a separate issue for c?

**Comment by csnyulas** [comment]
sure.
