### ISSUE TITLE
Cannot remove duplicate rdfs:label items.

### ISSUE THREAD

**Issue by zhuyan166** [protegeproject/webprotege#556]
Thanks for the resent update of displaying label of different language by specifying annotation properties. It's really helpful.

I am trying to add multiple rdfs:label items for different languages.  Some how, it doesn't work if I want to remove one of dupliate rdfs:label items.
And other annotation properties like rdfs:comment, rdfs:definition, also have this problem.

**Comment by zhuyan166** [comment]
![tim 20180930084139](https://user-images.githubusercontent.com/5309539/46251704-1239a280-c48d-11e8-924b-13db4e04c350.png)

**Comment by csnyulas** [comment]
Can you please clarify what does not work?
You are unable to remove one of those highlighted annotation properties? Or you don't see the label that you expect, after removing one of those properties? Or it is something else?
Could you please send us a screen shot with your project language settings ('Project -> Settings -> Display Name Settings`), and local language settings (shown in the `Display` menu).

**Comment by zhuyan166** [comment]
Right, I cannot remove any one of those highlighted annotation properties(rdfs:label) now.

Project language settings is OK for me. It can switch the different languages successfully, although it would be better if setting dialog has a button of "OK"  or "Apply" to refresh.

**Comment by csnyulas** [comment]
Would it be possible to share the project where you encounter this issue with "M Horridge" and "Csongor Nyulas" users, with editing access? We would like to see if we can reproduce the problem.

**Comment by csnyulas** [comment]
Thank you @zhuyan166 I can see now the problem. I tried to delete the "bearer of" and "...的载体" labels and even though it disappeared after clicking on the delete (X) icon, when I refreshed the content of the view, the labels reappeared. Interestingly there was no entry in the change history about this operation either. I wonder if those statements aren't coming from an imported ontology (not the root ontology), and that's why you can't delete them?
@matthewhorridge can you take a look at this?

**Comment by matthewhorridge** [comment]
Thanks @zhuyan166.  I've taken a look at the project and I know what the issue is – I just need to design and implement a fix for it.

**Comment by zhuyan166** [comment]
It works now！ thanks @csnyulas @matthewhorridge 
The delete operation log also shows in the change history.

![image](https://user-images.githubusercontent.com/5309539/46403954-7632c400-c736-11e8-96a3-e7a5544f7e11.png)

**Comment by csnyulas** [comment]
Excellent. Glad to hear that. You can unshare your ontology with us now.
