### ISSUE TITLE
Don't send notification emails to users who don't have "view" access to a given project any more

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#580]
Watches combined with email notifications are very nice feature of WebProtege. Once a user looses his or her access to view the project, they should not get any more notification about activity to the entities their watched before.

We can decide if we want to remove all the watched entities from the user at the moment they loose their viewing right, or we keep them (just in case they get back their access right to the project) in which case we need to test for access rights when the notifications are generated.

**Comment by dickersonlj** [comment]
Agreed.  This is an issue with our project as well, as we have several project team members, which occasionally rotate off the project. Lingering email alerts has forced us to use tagging more for tracking comments and edits.
