### ISSUE TITLE
Creating an external individual onthe fly (such as dbpedia:Boeing) will have the wrong IRI assigned

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#585]
One can create an individual with a known external prefixed name (e.g. `dbpedia:Boeing`)
in the "Individuals by Class" view and it will get the correct IRI (e.g. `http://dbpedia.org/resource/Boeing`)
![image](https://user-images.githubusercontent.com/2441046/47602941-47f17e80-d99a-11e8-84bb-ba4ff7ff07d6.png)

However if I create such individual on the fly, the wrong IRI is getting assigned (which in our example would be `wptmp:entity#dbpedia:Boeing`)

Unfortunately neither of these is clickable (or easy to lead it externally)

**Comment by matthewhorridge** [comment]
This is a mis-characterisation of the issue.  Also, it's not an issue of "internal" versus "external" (which doesn't really exist).  The behaviour that is reported is likely due to #592.  In any case, inline creation by specifying a prefixed name works as expected.
