### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by gabrieleparrino** [protegeproject/webprotege#588]
It stays in loading for ages and it doesn't work. Are you loading an upgrade or something?

**Comment by matthewhorridge** [comment]
Looking into it

**Comment by matthewhorridge** [comment]
@gabrieleparrino sorry for the inconvenience.  Please can you try to load your project again?  Things should be working now.  Thanks, Matthew

**Comment by gabrieleparrino** [comment]
Everything fixed. Thanks!
