### ISSUE TITLE
WebProtege application settings: Make project auto-discard time out configurable

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#596]
It would be really nice if the timeout for how long inactive (dormant) projects are kept loaded in the memory could be configured through the application settings. This could improve performance for installations that host a few large ontologies that they would prefer to keep in memory for longer time, to avoid the delay caused by reloading these project. The currently used 3 minutes time out may not be ideal for them.

Ideally administrators will be able to control this timeout in an even more flexible fashion in the future, i.e. per project, depending on project size, manually discarding projects, etc.

**Comment by matthewhorridge** [comment]
There's a whole bunch of issues for the same idea btw
