### ISSUE TITLE
Class Hierarchy view context menu "Merge into...": Commit message is incomplete

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#598]
The commit message for the "Merge into..." action does not contain the names of entities that are being merged and merged into, and as such are not very useful, unless they are edited manually, which can be quite painful.

**Comment by matthewhorridge** [comment]
Works as designed

**Comment by csnyulas** [comment]
It does seem to work as designed. I am not sure what were the circumstances where it didn't (maybe related to the display name settings, or something else), so I leave it closed.
