### ISSUE TITLE
All classes disappeared on webprotege.stanford.edu

### ISSUE THREAD

**Issue by muichkine** [protegeproject/webprotege#612]
Hello,

Over the weekend (06-07/04/2019) something changed in Webprotégé and all my data is gone.

![image](https://user-images.githubusercontent.com/2428966/55714957-f1ca4200-59f3-11e9-979b-5497933dd2ee.png)

I suspect this is linked to the migration to WebProtégé 4.0. Are we supposed to handle the data migration ourselves ?

**Comment by matthewhorridge** [comment]
@muichkine If you're seeing this problem on webprotege.stanford.edu then there's a problem somewhere.  Things should appear as normal.  Please could empty your browser caches and then refresh the page and see if this problem persists?

**Comment by matthewhorridge** [comment]
@muichkine I've done some digging and I believe that all WP data is intact... the problem that you experienced was freezing at the UI level.  Unfortunately, it's hard to reproduce (it happened once previously, but this was months ago), but I'm looking into it.  WebProtege should be working as expected now though.

**Comment by muichkine** [comment]
Yes it's all back. Thanks a lot.
