### ISSUE TITLE
Cannot re-open or upload ontology

### ISSUE THREAD

**Issue by AntoniaWild** [protegeproject/webprotege#620]
Hi all,

I used desktop Protege (latest release) and saved file in XML/RDF. Had problems with displaying/saving the annotations (though they appeared in the code when opening via Editor), so I created a new project loading the desktop ontology in Webprotege.

I added classes and properties in Webprotege (they received a new URI and I was unable to change all classes and properties to a single URI, always only the Webprotege one's were changed when using the built-in function and vice versa using the desktop functionality).

Now I downloaded it in OWL/XML, edited in the desktop version, saved it and when I wanted to reopen it in the desktop version, all instances were gone/ it was empty (though not in the Editor code).
Tried to upload to Webprotege by uploading under "creating a new project" (and another time using the upload/ merge function). It didn't work either (all empty).
Tried the same with Turtle, same outcome. Plus, tried on both Chrome and Firefox.

With RDF/XML it works, but I am afraid my annotations will get lost. Plus I have substantially edited the OWL/XML file on the desktop version in the meantime and would like to avoid having to do that all over. Changing the filename from OWX to OWL did also not help.

Could someone assist me with that?
Thank you in advance!

**Comment by matthewhorridge** [comment]
Hi @AntoniaWild,

Are you able to attach your RDF/XML ontology here?

**Comment by AntoniaWild** [comment]
@matthewhorridge Sent you the ontology via email

**Comment by matthewhorridge** [comment]
Resolved (IRI should have been literal)
