### ISSUE TITLE
"Upload and merge" only available to project creator

### ISSUE THREAD

**Issue by johnwjudkins** [protegeproject/webprotege#621]
On WebProtégé projects where I work with a colleague and we give each other editing privileges on the files we upload, we find that only the creator can upload and merge a local file to make changes. We would like WP to allow upload and merge for someone who has been given editing privileges by the original uploader.

**Comment by matthewhorridge** [comment]
@johnwjudkins can you make your college a "manager" for the project in the sharing settings page (or would this be too permissive)?  This would allow them to use upload and merge.

**Comment by johnwjudkins** [comment]
It still doesn't work.

Example: https://webprotege.stanford.edu/#projects/a8dfe883-5f2e-47dd-8466-abe3620a7f4f/edit/Classes

My coworker added me as a manager, but I still cannot upload and merge.

**Comment by matthewhorridge** [comment]
@johnwjudkins is the option still greyed out in the UI or does the upload and merge fail?

**Comment by johnwjudkins** [comment]
It's not grayed out - it just fails.

**Comment by matthewhorridge** [comment]
Is there an error message?  What is shown displayed after you press upload?

**Comment by johnwjudkins** [comment]
No error message. The image in the popup window (that normally shows an image of the changes made to the file) is empty.

**Comment by johnwjudkins** [comment]
OK, it works now with the project I sent you in the link, but it's not working with this project:

https://webprotege.stanford.edu/#projects/b9f04b1d-f0ee-4647-871c-49f4689ce600/edit/Classes

This is one that I own, and I made a coworker manager. She cannot upload and merge. It gives the empty image I just described.

**Comment by matthewhorridge** [comment]
Can you confirm that you coworker is: (1) Downloading a copy of the ontologies in the project, (2) modifying those ontologies, (3) Uploading the modified ontologies?

**Comment by johnwjudkins** [comment]
She can download and modify ontologies that I own. She can't upload and merge to one that I own.

**Comment by matthewhorridge** [comment]
How does she upload the file?  Is it in a zip file and is the ontology in the zip file call root-ontology.owl?

**Comment by johnwjudkins** [comment]
It's not a zip; it's an .owl file. This file has the same name as the one that was originally uploaded, if that matters.

**Comment by matthewhorridge** [comment]
If it's a file that's not zipped, then the name should not matter.  
Would you be able to post the exact file being uploaded here?

**Comment by johnwjudkins** [comment]
I just emailed it to you.

**Comment by matthewhorridge** [comment]
The reason for the empty file is due to the way the upload and merge functionality works.  The ontology IRI of the ontology being uploaded must match the ontology IRI of the ontology that was download.  This limitation is in place incase you edit multiple ontologies externally and upload them – WebProtege needs to figure out which ontology to diff.

So, for now, please ensure that your ontology IRIs match.

I admit that this is not ideal, at all.  Furthermore, there should be an explanation of this somewhere in the UI.  We need to sort this out.

**Comment by matthewhorridge** [comment]
Closing this. @johnwjudkins please comment if you need further assistance.
