### ISSUE TITLE
Support merging arbitrary ontologies into projects

### ISSUE THREAD

**Issue by manishksp** [protegeproject/webprotege#627]
When I upload and merge two owl file, I see the popup where we can see the **changes to be applied **, but it shows blank and after continue it shows the merge is successful. But I don't see the change applied. 

I tried the same in desktop protege and it worked fine by adding duplicate nodes after .

Please let me know what the error.

[Archive.zip](https://github.com/protegeproject/webprotege/files/3428616/Archive.zip)

**Comment by matthewhorridge** [comment]
@manishksp the merge in WebProtege isn't for merging two separate ontologies.  It's for merging external edits to an existing WebProtege ontology.  Also, the ontologies must have the same ontology IRIs.  Does this make sense?

**Comment by manishksp** [comment]
Thanks , I didn't know this , my bad. But can you guide me how to merge two ontologies using web protege ? I wanted to merge two ontologies or two separate owl file in rdf format.

**Comment by matthewhorridge** [comment]
No problem!  

We don't have this functionality in WebProtege.  I'll change the title of this issue so that it becomes a feature request.

**Comment by manishksp** [comment]
ok but this can be done through desktop protege ? As I see Merge Ontologies option there .

**Comment by matthewhorridge** [comment]
Yes, the desktop functionality is different.  It does what you want.  We are about to change the name of the merge functionality in WebProtege because it has confused people.

**Comment by manishksp** [comment]
thanks for the answer .

**Comment by matthewhorridge** [comment]
You're welcome!

**Comment by manishksp** [comment]
> @manishksp the merge in WebProtege isn't for merging two separate ontologies. It's for merging external edits to an existing WebProtege ontology. Also, the ontologies must have the same ontology IRIs. Does this make sense?

Please explain what do you mean by same ontology IRIs means.

**Comment by matthewhorridge** [comment]
The IRI of an ontology is an identifier for that ontology.  IRIs typically look like URL (Web addresses).  For WebProtege to be able to merge in external edits, it selects ontologies to merge based on the IRIs.

**Comment by manishksp** [comment]
ok got it , by when this enhancement can be expected to be complete .

**Comment by matthewhorridge** [comment]
> by when this enhancement can be expected to be complete
 
Sorry, I can't provide an answer to that.  We're busy with various things at the moment.

**Comment by gandharvm** [comment]
Hi ! I would like to work on this issue, if nobody is working on this, and if I get a green light and guidance from the maintainers.

**Comment by matthewhorridge** [comment]
@gandharvm you're most welcome to work on this!  Please let us know when you decide to start.

**Comment by gandharvm** [comment]
@matthewhorridge I'll start working on it asap. I wanted to know if the option to merge ontologies should be given to the user when creating a new project or should it be there in the Project drop-down menu only.

**Comment by matthewhorridge** [comment]
I think it would be simpler (easiest) if it's just in the Project drop-down, for now.

**Comment by gandharvm** [comment]
@matthewhorridge Do there need to be two separate options: one for applying external edits and one for merging different ontologies into a project? Can you help me figure out the difference between the two (other than the fact that we need the same to have the same ontology IRI for applying external edits while we can have separate IRIs for merging ontologies)?

**Comment by matthewhorridge** [comment]
I think separate are needed.  A merge only adds axioms, where as an edit computes a diff and adds/removes axioms as necessary.

I guess there could be an option to merge (add) axioms from an external ontology into a current ontology or create a new ontology in the project.

**Comment by gandharvm** [comment]
I have almost completed implementing the feature and was just testing it on my system. One problem that I am currently facing is if two or more ontologies are merged into a new ontology, and this revision is reverted, the new ontology is still present in the project but is now empty. Is there any way to add ontology creation to project history so that the ontology is also deleted when the revision is reverted?

**Comment by matthewhorridge** [comment]
Great question @gandharvm.  I think this needs to be sorted out.  Off the top of my head I'm not sure of the best way of doing this.  Needs some thought

**Comment by gandharvm** [comment]
Thanks a lot for your help @matthewhorridge. Would it be a bad idea if I create a separate issue for this? I think we can still have the feature of merging ontologies into a new ontology despite this issue. I only have to create the JUnit Tests, and I can finalise the PR and submit soon.

**Comment by matthewhorridge** [comment]
I think that's a perfectly acceptable idea @gandharvm
