### ISSUE TITLE
How can I use OntoCheck plugin in webprotege

### ISSUE THREAD

**Issue by manishksp** [protegeproject/webprotege#629]
I want to integrate the OntoCheck plugin in webProtege , is there any process to follow to use plugin in web protege . 

Second point I want to run validation on our ontology similar to like OntoCheck does , is there doc on this how we can build our own in Java ,or use this plugin . Help will be appreciated

**Comment by matthewhorridge** [comment]
It isn't possible to use OntoCheck in WebProtege.  However, WebProtege does have some kind of functionality that might be useful for you.  Can you give me a specific example (or a couple of examples) of the kinds of checks that you want to run?

**Comment by manishksp** [comment]
examples 
1.All annotations(Properties) will be lower cased. Ex is_numeric, is_abstract 
2.All relationships will have upper case : Ex ONT_PT_PCS_PT,PCS_PT_ONT_PT,IDENTITY_ATTR
3.All classes will be prefixed as described below and the class name itself will be lowercased 4.separated by underscore. PCS_ATTR_xxx, ONT_PT_xxx ,ONT_PT_ssss.
 5. mandatory and optional annotation properties

So mostly I need  Naming Conventions checks right now .  And it can run whenever document is changed and saved .

**Comment by matthewhorridge** [comment]
@manishksp you can encode these checks using the Tags feature in WebProtege.  Use the "Project" -> "Tags" menu item.  Then add tags e.g. to encode 1.

Create a tag that summarizes the violation 

<img width="857" alt="image" src="https://user-images.githubusercontent.com/488607/62484702-9b85c980-b76f-11e9-9472-44350c5a3bc9.png">

Add a condition that applies the tag

<img width="865" alt="image" src="https://user-images.githubusercontent.com/488607/62484738-af313000-b76f-11e9-9b6d-3c04124c3159.png">

You'll see tags in the hierarchy...

<img width="193" alt="image" src="https://user-images.githubusercontent.com/488607/62484778-c1ab6980-b76f-11e9-8d1b-f0bdeef448ed.png">

You can also search for them...

<img width="624" alt="image" src="https://user-images.githubusercontent.com/488607/62484807-d5ef6680-b76f-11e9-999d-8be28b8beb51.png">

I think you can pretty much encode all of what you want to encode.  If you have trouble let me know.

**Comment by manishksp** [comment]
Thanks a lot @matthewhorridge . Let me give it a try

**Comment by matthewhorridge** [comment]
Great.  Let me know if you have questions or feedback.

**Comment by matthewhorridge** [comment]
I'm closing this issue.  If you can't figure out how to do something with the tagging functionality please post your questions to the Protege mailing list.
