### ISSUE TITLE
Running version 4.0 behind a reverse proxy

### ISSUE THREAD

**Issue by hygt** [protegeproject/webprotege#631]
Hello,

I've successfully deployed the 4.0.0-beta-1 release internally.
However, as I'm trying to expose this deployment on my organization's public domain, I cannot figure out how to set up our nginx reverse proxy properly.

The GWT RPC requests seem to fail and I get the error:

> WebProtégé has been updated.  Please empty your browser caches and reload your browser.

If I look at the response from `dispatcherservice`, I can see

```
//EX[2,1,["com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException/3936916533","Type name elision in RPC payloads is only supported if the RPC whitelist file is used."],0,7]
```

Which if I understand correctly, happens because the module path doesn't match that of the internal deployment.

I'm no nginx expert, but I've tried the nginx directives `proxy_set_header` and a more convoluted way with `map` to rewrite the `X-GWT-Module-base` header, to no avail.

Do you have any input regarding the matter?
Thanks.

**Comment by matthewhorridge** [comment]
I don't have any experience with nginx.  I can go through some of our apache settings for WebProtege though.

You've correctly identified that the ```x-gwt-module-base``` header needs rewriting. We have a rewrite rule for request headers as follows:

```
RequestHeader edit x-gwt-module-base ^https://webprotege.stanford.edu/(.*)$ http://webprotege.stanford.edu:8080/webprotege/$1
```
We also needed set up ProxyPass and ProxyPassReverse as follows

```
 ProxyPass / http://localhost:8080/webprotege/
```  

```
ProxyPassReverse / http://localhost:8080/webprotege/
```

**Comment by matthewhorridge** [comment]
p.s. I also recalled that, in the tomcat default context.xml file we had to set the following:

```<Context sessionCookiePath="/">```

**Comment by hygt** [comment]
Hi @matthewhorridge 
Thank you for the deployment details.

I indeed tried a very similar approach but nothing worked.
I ended up redeploying WebProtégé to a context path that matches the external route and everything is working as expected.
I guess I will need to find someone who knows nginx better than me on our end. :smiley:

**Comment by matthewhorridge** [comment]
@hygt you're welcome.  Sorry you haven't managed to figure things out though.  Do you mind if I close this issue or do you think you'll want to add further things to it?

**Comment by hygt** [comment]
You can go ahead and close it. Thank you again.

**Comment by eriknl1982** [comment]
In case anyone is looking for a nginx solution, I managed to fix the issue by adding:

proxy_set_header x-gwt-module-base $scheme://$host/webprotege/;

this way I was able to run webprotege on http://mydomain.com/webprotege
