### ISSUE TITLE
https://webprotege.stanford.edu/ - Download of Ontologies not possible

### ISSUE THREAD

**Issue by Wolkenstein** [protegeproject/webprotege#664]
Dear developers,

unfortunately, it seems to be impossible to download an ontology from https://webprotege.stanford.edu/ at the moment. Server is not responding, format choice seems to be irrelevant. 

Thx 
Peter

**Comment by Wolkenstein** [comment]
Tested with Firefox, Chrome, Edge, Internetexplorer. No response

**Comment by rodriguesk** [comment]
Not working for me either. It was working like 9 days ago. So strange. I need this fix ASAP!

**Comment by alexanderpils** [comment]
Same problem here 😢

**Comment by rodriguesk** [comment]
Seems the dev team fixed this issue. Works now for me.

**Comment by Wolkenstein** [comment]
Yes it's fixed. Thank you and keep up the good work!
