### ISSUE TITLE
WebProtégé configured problem

### ISSUE THREAD

**Issue by Bodawen** [protegeproject/webprotege#668]
Hi everyone, I get some troubles when I build and run the project from source code. I need your help!

I followed steps from readme to clone Webprotege project from git and build the maven project. I downloaded the WebProtégé Command Line Tool to bootstrap WebProtégé with an admin account. 

Then I run the GWT code server and start the tomcat server. On http://localhost:8080/ I can log in with my admin account but cannot create a new project. On the middle top, there is a warning: **WebProtégé is not configured properly**.

I checked the Info from cmd:

> 2020-03-27 12:36:00.858  INFO   Found style customization file at C:\ProgramData\webprotege\webprotege.css
> 2020-03-27 12:36:00.936  WARN   System notification email address is not specified
> 2020-03-27 12:36:00.937  WARN   Application host is not specified
> 2020-03-27 12:36:00.939  WARN   Cannot construct well-formed application URL. (java.net.URISyntaxException: Expected hostname at index 8: https://:443)
> 2020-03-27 12:36:00.941  WARN   Cannot construct well-formed project URLs. (java.net.URISyntaxException: Expected hostname at index 8: https://:443#projects/60448433-38de-4dea-beef-62e607e3c334/edit/Classes)
> 2020-03-27 12:36:00.945  WARN   Cannot construct well-formed OWL Entity URLs. (java.net.URISyntaxException: Expected hostname at index 8: https://:443#projects/3b8a36da-7829-4e30-aef0-aa5c598deed2/edit/Classes?selection=Class(owl:Thing))

How can I solve the issue? Thanks

**Comment by lixiepeng** [comment]
Hi @Bodawen , How did you figure out this issue?

**Comment by Bodawen** [comment]
> Hi @Bodawen , How did you figure out this issue?

Just need to edit the WebProtégé settings, follow those steps

https://github.com/protegeproject/webprotege/wiki/WebProt%C3%A9g%C3%A9-4.0.0-beta-x-Installation#edit-the-webprot%C3%A9g%C3%A9-settings

**Comment by lixiepeng** [comment]
> Just need to edit the WebProtégé settings, follow those steps
https://my.server.address:8080/webprotege is 404

**Comment by Bodawen** [comment]
> > Just need to edit the WebProtégé settings, follow those steps
> 
> https://my.server.address:8080/webprotege is 404
> I use docker-compose

Can you check your server address? If you use docker and followed readme file, the default server address is http://localhost:5000

**Comment by lixiepeng** [comment]
It show that `WebProtégé is not configured properly` in header.

**Comment by Bodawen** [comment]
> It show that `WebProtégé is not configured properly` in header.

Then go to http://localhost:5000/webprotege#application/settings, and configure your information.
