### ISSUE TITLE
create an admin account with the version "4.0.0-beta-2"

### ISSUE THREAD

**Issue by marechau** [protegeproject/webprotege#674]
How to create an admin account with the version "4.0.0-beta-2". We do not find the jar webprotege-cli.jar

**Comment by matthewhorridge** [comment]
@marechau you can use the cli from beta-1.  It's [here](https://github.com/protegeproject/webprotege/releases/download/v4.0.0-beta-1/webprotege-cli-4.0.0-beta-1.jar)
