### ISSUE TITLE
Link to changed entity in the notification email does not work

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#72]
Current:

You can view this Class at the link below:
http://webprotege.stanford.edu#Edit:projectId=987d9f04-f085-4534-be1f-8619aa5f0c4d;tab=ClassesTab&id=http%3A%2F%2Fwebprotege.stanford.edu%2FRBW4DSH2394zxtPwdHEMDeW

**Comment by matthewhorridge** [comment]
Fixed in WebProtege 3.0.0
