### ISSUE TITLE
Publish Aero ontology shown in webprotege screenshots

### ISSUE THREAD

**Issue by fbuchinger** [protegeproject/webprotege#736]
Would it be possible to publish the aero ontology (.owl file) that is shown in various webprotege documents and papers?  (E.g. https://arxiv.org/ftp/arxiv/papers/1902/1902.08251.pdf - figure 1)
I'd like to use it as a starting point for my own experiments in webprotege.

Thanks,

Franz

**Comment by matthewhorridge** [comment]
Good idea!  I've just published it at https://protege.stanford.edu/ontologies/aero
