### ISSUE TITLE
Public shared link not available

### ISSUE THREAD

**Issue by mechatronics123** [protegeproject/webprotege#796]
Hi, we would like to share the ontology link with public. In the share tab, it says anyone with link can view the ontology (of course sign-in is required):
![image](https://github.com/protegeproject/webprotege/assets/67400427/effa2fa3-0ce6-4b63-8e58-05da6b653f38)

What constructs the public link\, and how to produce it?

Thanks!

**Comment by matthewhorridge** [comment]
This isn't obvious... you can just copy the link from the browser when you are viewing the Classes Tab (or another Tab of your choice).  Let me know if you have questions.

**Comment by mechatronics123** [comment]
Perfect! Thank you
